### ISSUE TITLE
SeAT Crash

### ISSUE THREAD

**Issue by shibdib** [eveseat/seat#131]
SeAT crashed at some point tonight, see below for the log. 

Website only said "Whoops, looks like something went wrong." 

Latest version of seat, on ubuntu 14.04 

```
[2016-09-02 07:01:58] local.ERROR: exception 'Predis\Connection\ConnectionException' with message 'Connection refused [tcp://127.0.0.1:6379]' in /var/ww$
Stack trace:
#0 /var/www/seat/vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\Connection\AbstractConnection->onConnectionError('Connection refu$
#1 /var/www/seat/vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\Connection\StreamConnection->createStreamSocket(Object(Predis\Con$
#2 /var/www/seat/vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\Connection\StreamConnection->tcpStreamInitializer(Object(Predis\C$
#3 /var/www/seat/vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\Connection\StreamConnection->createResource()
#4 /var/www/seat/vendor/predis/predis/src/Connection/StreamConnection.php(258): Predis\Connection\AbstractConnection->connect()
#5 /var/www/seat/vendor/predis/predis/src/Connection/AbstractConnection.php(180): Predis\Connection\StreamConnection->connect()
#6 /var/www/seat/vendor/predis/predis/src/Connection/StreamConnection.php(288): Predis\Connection\AbstractConnection->getResource()
#7 /var/www/seat/vendor/predis/predis/src/Connection/StreamConnection.php(394): Predis\Connection\StreamConnection->write('*2\r\n$5\r\nWATCH\r\n...')
#8 /var/www/seat/vendor/predis/predis/src/Connection/AbstractConnection.php(110): Predis\Connection\StreamConnection->writeRequest(Object(Predis\Command$
#9 /var/www/seat/vendor/predis/predis/src/Client.php(331): Predis\Connection\AbstractConnection->executeCommand(Object(Predis\Command\TransactionWatch))
#10 /var/www/seat/vendor/predis/predis/src/Transaction/MultiExec.php(179): Predis\Client->executeCommand(Object(Predis\Command\TransactionWatch))
#11 /var/www/seat/vendor/predis/predis/src/Transaction/MultiExec.php(239): Predis\Transaction\MultiExec->call('WATCH', Array)
#12 /var/www/seat/vendor/predis/predis/src/Transaction/MultiExec.php(132): Predis\Transaction\MultiExec->watch('queues:high:del...')
#13 /var/www/seat/vendor/predis/predis/src/Transaction/MultiExec.php(200): Predis\Transaction\MultiExec->initialize()
#14 /var/www/seat/vendor/predis/predis/src/Transaction/MultiExec.php(162): Predis\Transaction\MultiExec->executeCommand(Object(Predis\Command\ZSetRangeB$
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(210): Predis\Transaction\MultiExec->__call('zrangebyscore', Array)
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(210): Predis\Transaction\MultiExec->zrangebyscore('queues:high:del...', '$
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(187): Illuminate\Queue\RedisQueue->getExpiredJobs(Object(Predis\Transacti$
#18 [internal function]: Illuminate\Queue\RedisQueue->Illuminate\Queue\{closure}(Object(Predis\Transaction\MultiExec))
#19 /var/www/seat/vendor/predis/predis/src/Transaction/MultiExec.php(431): call_user_func(Object(Closure), Object(Predis\Transaction\MultiExec))
#20 /var/www/seat/vendor/predis/predis/src/Transaction/MultiExec.php(368): Predis\Transaction\MultiExec->executeTransactionBlock(Object(Closure))
#21 /var/www/seat/vendor/predis/predis/src/Client.php(477): Predis\Transaction\MultiExec->execute(Object(Closure))
#22 /var/www/seat/vendor/predis/predis/src/Client.php(401): Predis\Client->createTransaction(Array, Object(Closure))
#23 /var/www/seat/vendor/predis/predis/src/Client.php(461): Predis\Client->sharedContextFactory('createTransacti...', Array)
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(197): Predis\Client->transaction(Array, Object(Closure))
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(165): Illuminate\Queue\RedisQueue->migrateExpiredJobs('queues:high:del...$
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(133): Illuminate\Queue\RedisQueue->migrateAllExpiredJobs('queues:high')
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(181): Illuminate\Queue\RedisQueue->pop('high')
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(151): Illuminate\Queue\Worker->getNextJob(Object(Illuminate\Queue\RedisQueue)$
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(109): Illuminate\Queue\Worker->pop('', 'high,medium,low...', '0'$
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(71): Illuminate\Queue\Console\WorkCommand->runWorker('', 'high,m$
#31 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#32 /var/www/seat/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array)
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#34 /var/www/seat/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput)$
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Compon$
#36 /var/www/seat/vendor/symfony/console/Application.php(841): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object$
#37 /var/www/seat/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkC$
#38 /var/www/seat/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvI$
#39 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\$
#40 /var/www/seat/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\$
#41 {main}


```

**Comment by leonjza** [comment]
Make sure your redis server is up and running. You can try something like `service redis restart` and see if that helps.

**Comment by shibdib** [comment]
Might have been the issue, just did a full system restart and it's working now

**Comment by leonjza** [comment]
:+1:

**Comment by shibdib** [comment]
Re-opening. Sire is down again, restart was only a temporary fix

**Comment by leonjza** [comment]
You should investigate why redis goes down. Nothing we can do in SeAT itself for that. SeAT will be upset, and rightfully so when redis is no longer available.

**Comment by shibdib** [comment]
Any idea where the redis log is?

**Comment by leonjza** [comment]
Join us on slack then I can try and help you faster: http://seat-docs.readthedocs.io/en/latest/contact/#slack

**Comment by warlof** [comment]
Can you shiw us your firewall rules ?
`sudo iptables -L`

**Comment by shibdib** [comment]
it's not the firewall or redis (redis logs look fine and restarting redis doesn't do anything)

**Comment by warlof** [comment]
What are your server spec ? Especially ram/swap

**Comment by shibdib** [comment]
```
             total       used       free     shared    buffers     cached
Mem:          2001       1935         66         18         25        142
-/+ buffers/cache:       1766        235
Swap:         2047        934       1113
```

mysqld is the main memory eater. 

http://i.imgur.com/QzsVANW.png

Would rather avoid upgrading the droplet because it doubles the price

**Comment by shibdib** [comment]
Gonna mess with my.cnf and try to get mem usage down, think that's the issue. Should be safe to close this
