### ISSUE TITLE
On Insert Into Corporation_Customs_Offices, 'AllowAllinace' Column Incorrect integer value: true

### ISSUE THREAD

**Issue by mthomas92868** [eveseat/seat#153]
```
Last Updater: Processing: CustomsOffices

Exception       : Illuminate\Database\QueryException
Error Code      : HY000
Error Message   : SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'True' for column 'allowAlliance' at row 1 (SQL: insert into `corporation_customs_offices` (`corporationID`, `itemID`, `solarSystemID`, `solarSystemName`, `reinforceHour`, `allowAlliance`, `allowStandings`, `standingLevel`, `taxRateAlliance`, `taxRateCorp`, `taxRateStandingHigh`, `taxRateStandingGood`, `taxRateStandingNeutral`, `taxRateStandingBad`, `taxRateStandingHorrible`, `updated_at`, `created_at`) values (98458525, 1021815204636, 30004569, 9R4-EJ, 21, True, True, -10, 0.1, 0, 0.05, 0.1, 0.1, 0.1, 0.1, 2016-12-10 03:07:14, 2016-12-10 03:07:14))
File            : /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php
Line            : 769

Traceback: 
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(725): Illuminate\Database\Connection->runQueryCallback('insert into `co...', Array, Object(Closure))
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(480): Illuminate\Database\Connection->run('insert into `co...', Array, Object(Closure))
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(434): Illuminate\Database\Connection->statement('insert into `co...', Array)
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `co...', Array)
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2152): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `co...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1464): call_user_func_array(Array, Array)
#7 /var/www/seat/bootstrap/cache/compiled.php(10823): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /var/www/seat/bootstrap/cache/compiled.php(10812): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#9 /var/www/seat/bootstrap/cache/compiled.php(10766): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#10 /var/www/seat/bootstrap/cache/compiled.php(10424): Illuminate\Database\Eloquent\Model->save()
#11 /var/www/seat/vendor/eveseat/eveapi/src/Api/Corporation/CustomsOffices.php(69): Illuminate\Database\Eloquent\Model::create(Array)
#12 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/UpdateAuthenticated.php(62): Seat\Eveapi\Api\Corporation\CustomsOffices->call()
#13 [internal function]: Seat\Eveapi\Jobs\UpdateAuthenticated->handle()
#14 /var/www/seat/bootstrap/cache/compiled.php(1271): call_user_func_array(Array, Array)
#15 /var/www/seat/bootstrap/cache/compiled.php(9792): Illuminate\Container\Container->call(Array)
#16 /var/www/seat/bootstrap/cache/compiled.php(9907): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#17 /var/www/seat/bootstrap/cache/compiled.php(9885): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#18 /var/www/seat/bootstrap/cache/compiled.php(9795): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(47): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\UpdateAuthenticated), false)
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(73): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(201): Illuminate\Queue\Jobs\Job->fire()
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(150): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->runNextJob('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(83): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high,medium,low...')
#25 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#26 /var/www/seat/bootstrap/cache/compiled.php(1271): call_user_func_array(Array, Array)
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#28 /var/www/seat/vendor/symfony/console/Command/Command.php(254): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/seat/vendor/symfony/console/Application.php(820): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/seat/vendor/symfony/console/Application.php(187): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/seat/vendor/symfony/console/Application.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/seat/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 {main}
```

**Comment by leonjza** [comment]
Thanks. Someone on Slack also mentioned this one. Will fix it today.

**Comment by leonjza** [comment]
Will be fixed in the next tagged release today. I dont have an API key with POCO info, however I tested with:

```
» php artisan tinker
Psy Shell v0.7.2 (PHP 7.0.13 — cli) by Justin Hileman
>>> $a = '1';
=> "1"
>>> dump((int) $a);
1
=> null
>>> $a = '0';
=> "0"
>>> dump((int) $a);
0
=> null
>>>
```

**Comment by mthomas92868** [comment]
Confirmed Fixed, by doing manually fix...

**Comment by leonjza** [comment]
Thanks for the feedback.
