### ISSUE TITLE
 SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'accessMask' at row 1

### ISSUE THREAD

**Issue by mthomas92868** [eveseat/seat#155]
```
Last Updater: Processing: CallList

Exception       : Illuminate\Database\QueryException
Error Code      : 22003
Error Message   : SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'accessMask' at row 1 (SQL: insert into `eve_api_call_lists` (`name`, `type`, `accessMask`, `description`, `updated_at`, `created_at`) values (Clones, Character, 2147483648, List of your implants, attributes, jump clones, and jump fatigue timers., 2016-12-11 02:00:04, 2016-12-11 02:00:04))
File            : /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php
Line            : 769

Traceback: 
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(725): Illuminate\Database\Connection->runQueryCallback('insert into `ev...', Array, Object(Closure))
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(480): Illuminate\Database\Connection->run('insert into `ev...', Array, Object(Closure))
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(434): Illuminate\Database\Connection->statement('insert into `ev...', Array)
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `ev...', Array)
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2152): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ev...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1464): call_user_func_array(Array, Array)
#7 /var/www/seat/bootstrap/cache/compiled.php(10823): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /var/www/seat/bootstrap/cache/compiled.php(10812): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#9 /var/www/seat/bootstrap/cache/compiled.php(10766): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#10 /var/www/seat/vendor/eveseat/eveapi/src/Api/Api/CallList.php(58): Illuminate\Database\Eloquent\Model->save()
#11 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/UpdatePublic.php(60): Seat\Eveapi\Api\Api\CallList->call()
#12 [internal function]: Seat\Eveapi\Jobs\UpdatePublic->handle()
#13 /var/www/seat/bootstrap/cache/compiled.php(1271): call_user_func_array(Array, Array)
#14 /var/www/seat/bootstrap/cache/compiled.php(9792): Illuminate\Container\Container->call(Array)
#15 /var/www/seat/bootstrap/cache/compiled.php(9907): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\UpdatePublic))
#16 /var/www/seat/bootstrap/cache/compiled.php(9885): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\UpdatePublic))
#17 /var/www/seat/bootstrap/cache/compiled.php(9795): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(47): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\UpdatePublic), false)
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(73): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(201): Illuminate\Queue\Jobs\Job->fire()
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(150): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->runNextJob('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(83): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high,medium,low...')
#24 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#25 /var/www/seat/bootstrap/cache/compiled.php(1271): call_user_func_array(Array, Array)
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#27 /var/www/seat/vendor/symfony/console/Command/Command.php(254): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/seat/vendor/symfony/console/Application.php(820): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/seat/vendor/symfony/console/Application.php(187): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/seat/vendor/symfony/console/Application.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/seat/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 {main}
```

**Comment by imacxx** [comment]
Same bug in laravel 5.5

**Comment by warlof** [comment]
@imacxx good news since standard SeAT is not supporting laravel 5.5 :)

**Comment by chaymag** [comment]
I'm using laravel 5.6 any help with this issue ?

**Comment by warlof** [comment]
It's related to both deprecated xAPI and SeAT 2.

So... No support. Move to SeAT 3.0.
