### ISSUE TITLE
Member Security Exception

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#159]
I keep getting this error when jobs process.  What does it mean?

```
Last Updater: Processing: MemberSecurity

Exception       : ErrorException
Error Code      : 0
Error Message   : Undefined index: titles
File            : /var/www/seat/vendor/3rdpartyeve/phealng/lib/Pheal/Core/RowSetRow.php
Line            : 66

Traceback: 
#0 /var/www/seat/vendor/3rdpartyeve/phealng/lib/Pheal/Core/RowSetRow.php(66): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/seat/v...', 66, Array)
#1 /var/www/seat/vendor/eveseat/eveapi/src/Api/Corporation/MemberSecurity.php(79): Pheal\Core\RowSetRow->__get('titles')
#2 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/UpdateAuthenticated.php(62): Seat\Eveapi\Api\Corporation\MemberSecurity->call()
#3 [internal function]: Seat\Eveapi\Jobs\UpdateAuthenticated->handle()
#4 /var/www/seat/bootstrap/cache/compiled.php(1271): call_user_func_array(Array, Array)
#5 /var/www/seat/bootstrap/cache/compiled.php(9792): Illuminate\Container\Container->call(Array)
#6 /var/www/seat/bootstrap/cache/compiled.php(9907): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#7 /var/www/seat/bootstrap/cache/compiled.php(9885): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#8 /var/www/seat/bootstrap/cache/compiled.php(9795): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(47): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\UpdateAuthenticated), false)
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(73): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(201): Illuminate\Queue\Jobs\Job->fire()
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(150): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(75): Illuminate\Queue\Worker->runNextJob('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(83): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high,medium,low...')
#16 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#17 /var/www/seat/bootstrap/cache/compiled.php(1271): call_user_func_array(Array, Array)
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#19 /var/www/seat/vendor/symfony/console/Command/Command.php(254): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/seat/vendor/symfony/console/Application.php(820): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/seat/vendor/symfony/console/Application.php(187): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/seat/vendor/symfony/console/Application.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/seat/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 {main}
```

**Comment by leonjza** [comment]
Second report of this that I see. Not sure if CCP changed something in the API, so will add a check for it to make sure the key exists first.

**Comment by leonjza** [comment]
Ow. Ok so it looks like the check is already built in. Need to figure out why its not working as expected then.

**Comment by leonjza** [comment]
I am struggling to replicate this. If someone comes across the problem and is willing to share an API key with me, please come and talk to me on Slack. You can generate me a new temp key with just the _Titles_ access granted too.

![http://i.imgur.com/XPukIHJ.png](http://i.imgur.com/XPukIHJ.png)

**Comment by drkthunder02** [comment]
Where do I find how to get on Slack and can get you an API key as most of my API keys have the issue?

**Comment by leonjza** [comment]
In the SeAT docs [here](http://seat-docs.readthedocs.io/en/latest/contact/#slack) :)

**Comment by leonjza** [comment]
Had someone on Slack mention that kicking Dust characters from their corp fixed the problem.
