### ISSUE TITLE
stuck in log in page

### ISSUE THREAD

**Issue by asura12th** [eveseat/seat#193]
* **Problem**: Stuck in log in page.

* **Logs / Screenshots / Proof**
http://i.imgur.com/IWvp334.jpg

```
 * Getting environment information
Current User: allianceserver
PHP Version: 7.1.3-3+deb.sury.org~trusty+1
Host OS: Linux 12th 4.4.0-59-generic #80~14.04.1-Ubuntu SMP Fri Jan 6 18:02:02 UTC 2017 x86_64
SeAT Basepath: /var/www/seat

 * Checking DEBUG mode
Debug mode disabled

 * Checking storage
/var/www/seat/storage is writable
/var/www/seat/storage/app/pheal/ is writable
/var/www/seat/storage/sde/ is writable
/var/www/seat/storage/logs/laravel.log is writable

 * Checking Database
+------------+------------+
| Setting    | Value      |
+------------+------------+
| Connection | mysql      |
| Host       | 127.0.0.1  |
| Database   | seat       |
| Username   | seat       |
| Password   | ********** |
+------------+------------+
Connection OK to database: seat

 * Checking Redis
+----------+-----------+
| Setting  | Value     |
+----------+-----------+
| Host     | 127.0.0.1 |
| Port     | 6379      |
| Database | 0         |
+----------+-----------+
Connected to Redis
Set random key of: rWUFyuXdIm9JjH5GQSZgbcbW5atUQRzuoxWf9xjWPxuvf4OfInlUmIcEpQScQk8r
Set key to expire in 10 sec
Read key OK

 * Checking Pheal EVE API Access
Server Online: True
Online Players: 18710

Checking Local and Github Versions. Please wait...
+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 2.0.7         | 2.0.7         |
| Console       | 2.0.4         | 2.0.4         |
| Eveapi        | 2.0.10        | 2.0.10        |
| Notifications | 2.0.8         | 2.0.8         |
| Web           | 2.0.13        | 2.0.13        |
| Services      | 2.0.8         | 2.0.8         |
+---------------+---------------+---------------+
SeAT Diagnostics complete
```

leravel-2017-03-28.log
```
[2017-03-28 07:25:41] local.ERROR: ErrorException: file_put_contents(/var/www/seat/resources/views/vendor/notifications/email-plain.blade.php): failed to open stream: Permission denied in /var/www/seat/vendor/league/flysystem/src/Adapte$
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/seat/v...', 198, Array)
#1 /var/www/seat/vendor/league/flysystem/src/Adapter/Local.php(198): file_put_contents('/var/www/seat/r...', '<?php\n\nif (! em...', 2)
#2 /var/www/seat/vendor/league/flysystem/src/Filesystem.php(98): League\Flysystem\Adapter\Local->update('email-plain.bla...', '<?php\n\nif (! em...', Object(League\Flysystem\Config))
#3 [internal function]: League\Flysystem\Filesystem->put('email-plain.bla...', '<?php\n\nif (! em...')
#4 /var/www/seat/vendor/league/flysystem/src/MountManager.php(288): call_user_func_array(Array, Array)
#5 /var/www/seat/vendor/league/flysystem/src/MountManager.php(188): League\Flysystem\MountManager->invokePluginOnFilesystem('put', Array, 'to')
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/VendorPublishCommand.php(131): League\Flysystem\MountManager->__call('put', Array)
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/VendorPublishCommand.php(86): Illuminate\Foundation\Console\VendorPublishCommand->publishDirectory('/var/www/seat/v...', '/var/www/seat/r...')
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/VendorPublishCommand.php(62): Illuminate\Foundation\Console\VendorPublishCommand->publishTag(NULL)
#9 [internal function]: Illuminate\Foundation\Console\VendorPublishCommand->fire()
#10 /var/www/seat/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#12 /var/www/seat/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/seat/vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/seat/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\VendorPublishCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Sym$
#16 /var/www/seat/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleO$
#18 /var/www/seat/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 {main}
```

* **Version Info**: 
```
$ php -v
PHP 7.1.3-3+deb.sury.org~trusty+1 (cli) (built: Mar 25 2017 14:24:10) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3-3+deb.sury.org~trusty+1, Copyright (c) 1999-2017, by Zend Technologies
```
and web.local/phpinfo.php is showing good too.

fyi,
OS : UBUNTU 14 
Redis : 3.2.6

can someone help me? :(

**Comment by asura12th** [comment]
it works now!
/var/www/seat/.env
`APP_ENV=local` => 'APP_ENV=production'

/var/www/seat/routes/web.php
```
<?php

if (App::environment('production')) {
    URL::forceSchema('https');
}

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});
```

thank you everyone #support in slack
