### ISSUE TITLE
Integrity constraint violations character_character_sheet_jump_clones

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#194]
I'm getting the following error repeatedly (roughly 200) over the last weeks, related to varying API's

OS: Debian, Apache/2.4.10 (Debian)
PHP 7.0.17-1~dotdeb+8.1 (cli) ( NTS )
Mysql 5.5.54-0+deb8u1

Latest versions of SeAT

```
Last Updater: 

Exception       : Illuminate\Database\QueryException
Error Code      : 23000
Error Message   : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '19599731' for key 'PRIMARY' (SQL: insert into `character_character_sheet_jump_clones` (`jumpCloneID`, `characterID`, `typeID`, `locationID`, `cloneName`, `updated_at`, `created_at`) values (19599731, 216209346, 164, 61000249, , 2017-03-09 15:04:11, 2017-03-09 15:04:11))
File            : /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php
Line            : 770


Traceback: 
#0 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(726): Illuminate\Database\Connection->runQueryCallback('insert into `ch...', Array, Object(Closure))
#1 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(481): Illuminate\Database\Connection->run('insert into `ch...', Array, Object(Closure))
#2 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(435): Illuminate\Database\Connection->statement('insert into `ch...', Array)
#3 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `ch...', Array)
#4 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2154): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ch...', Array, 'jumpCloneID')
#5 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1470): Illuminate\Database\Query\Builder->insertGetId(Array, 'jumpCloneID')
#6 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(11001): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#7 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(10987): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#8 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(10941): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#9 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(284): Illuminate\Database\Eloquent\Model->save()
#10 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(11826): Illuminate\Database\Eloquent\Builder->updateOrCreate(Array, Array)
#11 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(11830): Illuminate\Database\Eloquent\Model->__call('updateOrCreate', Array)
#12 /var/www/seat.tgrads.com/vendor/eveseat/eveapi/src/Api/Character/CharacterSheet.php(144): Illuminate\Database\Eloquent\Model::__callStatic('updateOrCreate', Array)
#13 /var/www/seat.tgrads.com/vendor/eveseat/eveapi/src/Jobs/UpdateAuthenticated.php(78): Seat\Eveapi\Api\Character\CharacterSheet->call()
#14 [internal function]: Seat\Eveapi\Jobs\UpdateAuthenticated->handle()
#15 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#16 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(9961): Illuminate\Container\Container->call(Array)
#17 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(10076): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#18 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(10054): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#19 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(9964): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(47): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\UpdateAuthenticated), false)
#21 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(73): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#22 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(203): Illuminate\Queue\Jobs\Job->fire()
#23 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(152): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#24 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(75): Illuminate\Queue\Worker->runNextJob('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#25 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#26 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(83): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high,medium,low...')
#27 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#28 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#29 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#30 /var/www/seat.tgrads.com/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/seat.tgrads.com/vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/seat.tgrads.com/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/seat.tgrads.com/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/seat.tgrads.com/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 {main}
```

* **Problem**: _Whats wrong?_
* **Expected**: _What did you expect to happen?_
* **Logs / Screenshots / Proof**: _The more information you give the better!_
* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

**Comment by warlof** [comment]
Can you provide seat packages version ?
I think you're running an outdated platform.

**Comment by kwazulueve** [comment]
SeAT Api
Installed: v2.0.7
SeAT Console
Installed: v2.0.4
SeAT Eveapi
Installed: v2.0.10
SeAT Notifications
Installed: v2.0.8
SeAT Web
Installed: v2.0.13
SeAT Services
Installed: v2.0.8

**Comment by IvandaNothabeer** [comment]
Not fixed. Bug is still there.

**Comment by leonjza** [comment]
Jobs got a major overhaul in 3x. Lets see how it goes there.
