### ISSUE TITLE
Integrity constraint violations character_wallet_journals

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#195]
I've had the following error roughly 24 times over the last weeks, related to varying API's

OS: Debian, Apache/2.4.10 (Debian)
PHP 7.0.17-1~dotdeb+8.1 (cli) ( NTS )
Mysql 5.5.54-0+deb8u1

Latest versions of SeAT

```
Last Updater: 

Exception       : Illuminate\Database\QueryException
Error Code      : 23000
Error Message   : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'bd9493fbb12e3ae6d8adfc74bc5e4b8b' for key 'PRIMARY' (SQL: insert into `character_wallet_journals` (`characterID`, `hash`, `refID`, `date`, `refTypeID`, `ownerName1`, `ownerID1`, `ownerName2`, `ownerID2`, `argName1`, `argID1`, `amount`, `balance`, `reason`, `taxReceiverID`, `taxAmount`, `owner1TypeID`, `owner2TypeID`, `updated_at`, `created_at`) values (1286890556, bd9493fbb12e3ae6d8adfc74bc5e4b8b, 13872178392, 2017-03-21 20:58:31, 54, Balaganoff, 1286890556, Secure Commerce Commission, 1000132, , 0, -48.25, 113857430298.31, , , , 1376, 2, 2017-03-21 21:05:07, 2017-03-21 21:05:07))
File            : /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php
Line            : 770

Traceback: 
#0 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(726): Illuminate\Database\Connection->runQueryCallback('insert into `ch...', Array, Object(Closure))
#1 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(481): Illuminate\Database\Connection->run('insert into `ch...', Array, Object(Closure))
#2 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(435): Illuminate\Database\Connection->statement('insert into `ch...', Array)
#3 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `ch...', Array)
#4 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2154): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ch...', Array, 'hash')
#5 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1470): Illuminate\Database\Query\Builder->insertGetId(Array, 'hash')
#6 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(11001): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#7 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(10987): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#8 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(10941): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#9 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(10599): Illuminate\Database\Eloquent\Model->save()
#10 /var/www/seat.tgrads.com/vendor/eveseat/eveapi/src/Api/Character/WalletJournal.php(143): Illuminate\Database\Eloquent\Model::create(Array)
#11 /var/www/seat.tgrads.com/vendor/eveseat/eveapi/src/Jobs/UpdateAuthenticated.php(78): Seat\Eveapi\Api\Character\WalletJournal->call()
#12 [internal function]: Seat\Eveapi\Jobs\UpdateAuthenticated->handle()
#13 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#14 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(9961): Illuminate\Container\Container->call(Array)
#15 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(10076): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#16 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(10054): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#17 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(9964): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(47): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\UpdateAuthenticated), false)
#19 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(73): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#20 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(203): Illuminate\Queue\Jobs\Job->fire()
#21 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(152): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#22 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(75): Illuminate\Queue\Worker->runNextJob('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#23 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#24 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(83): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high,medium,low...')
#25 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#26 /var/www/seat.tgrads.com/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#27 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#28 /var/www/seat.tgrads.com/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/seat.tgrads.com/vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/seat.tgrads.com/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/seat.tgrads.com/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/seat.tgrads.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/seat.tgrads.com/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 {main}
```

**Comment by leonjza** [comment]
How many workers do you have running at the moment @kwazulueve ?

**Comment by kwazulueve** [comment]
Four. I notice that I get less errors now that I run member API keys only once per day instead of every hour, but they do still occur. Anyway it is not a big deal atm.
