### ISSUE TITLE
Assets view error

### ISSUE THREAD

**Issue by l0ser140** [eveseat/seat#20]
I've got error page when trying to view any assets on fresh setup
 ```
Whoops, looks like something went wrong.
```
This is appeared in logs.
```
[2015-12-23 15:12:39] local.ERROR: exception 'Symfony\Component\Intl\Exception\MethodArgumentValueNotImplementedException' with message 'The Symfony\Component\Intl\NumberFormatter\NumberFormatter::__construct() method's argument $style value 0 behavior is not implemented. The available styles are: CURRENCY, DECIMAL..  Please install the "intl" extension for full localization capabilities.' in /var/www/seat/vendor/symfony/intl/NumberFormatter/NumberFormatter.php:292
Stack trace:
#0 /var/www/seat/vendor/coduo/php-humanizer/src/Coduo/PHPHumanizer/String/MetricSuffix.php(49): Symfony\Component\Intl\NumberFormatter\NumberFormatter->__construct('en', 0)
#1 /var/www/seat/vendor/coduo/php-humanizer/src/Coduo/PHPHumanizer/Number.php(51): Coduo\PHPHumanizer\String\MetricSuffix->convert()
#2 /var/www/seat/vendor/eveseat/services/src/Helpers/helpers.php(139): Coduo\PHPHumanizer\Number::metricSuffix(28100)
#3 /var/www/seat/storage/framework/views/0886796b066f78700b09117c1697bdd9(32): number_metric(28100)
#4 /var/www/seat/bootstrap/cache/compiled.php(14629): include('/var/www/seat/s...')
#5 /var/www/seat/bootstrap/cache/compiled.php(14665): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/seat/s...', Array)
#6 /var/www/seat/bootstrap/cache/compiled.php(14498): Illuminate\View\Engines\CompilerEngine->get('/var/www/seat/v...', Array)
#7 /var/www/seat/bootstrap/cache/compiled.php(14486): Illuminate\View\View->getContents()
#8 /var/www/seat/bootstrap/cache/compiled.php(14477): Illuminate\View\View->renderContents()
#9 /var/www/seat/bootstrap/cache/compiled.php(15626): Illuminate\View\View->render()
#10 /var/www/seat/bootstrap/cache/compiled.php(15141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#11 /var/www/seat/bootstrap/cache/compiled.php(7695): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#12 /var/www/seat/bootstrap/cache/compiled.php(8922): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#13 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/seat/bootstrap/cache/compiled.php(9592): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/seat/bootstrap/cache/compiled.php(9574): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 /var/www/seat/bootstrap/cache/compiled.php(8923): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 /var/www/seat/bootstrap/cache/compiled.php(8908): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Seat\Web\Http\Controllers\Character\ViewController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'getAssets')
#19 /var/www/seat/bootstrap/cache/compiled.php(7862): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Seat\\Web\\Http\\C...', 'getAssets')
#20 /var/www/seat/bootstrap/cache/compiled.php(7833): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#21 /var/www/seat/bootstrap/cache/compiled.php(7486): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/seat/bootstrap/cache/compiled.php(9592): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/CharacterBouncer.php(69): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Seat\Web\Http\Middleware\CharacterBouncer->handle(Object(Illuminate\Http\Request), Object(Closure), 'assets')
#26 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#27 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/Authenticate.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Seat\Web\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/seat/bootstrap/cache/compiled.php(9574): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 /var/www/seat/bootstrap/cache/compiled.php(7487): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#33 /var/www/seat/bootstrap/cache/compiled.php(7475): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#34 /var/www/seat/bootstrap/cache/compiled.php(7460): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#35 /var/www/seat/bootstrap/cache/compiled.php(2307): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/seat/bootstrap/cache/compiled.php(9592): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /var/www/seat/bootstrap/cache/compiled.php(2925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#41 /var/www/seat/bootstrap/cache/compiled.php(12952): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#44 /var/www/seat/bootstrap/cache/compiled.php(11549): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#47 /var/www/seat/bootstrap/cache/compiled.php(12689): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#50 /var/www/seat/bootstrap/cache/compiled.php(12626): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#53 /var/www/seat/bootstrap/cache/compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#56 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/seat/bootstrap/cache/compiled.php(9574): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#58 /var/www/seat/bootstrap/cache/compiled.php(2254): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#59 /var/www/seat/bootstrap/cache/compiled.php(2237): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#60 /var/www/seat/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#61 {main}

Next exception 'ErrorException' with message 'The Symfony\Component\Intl\NumberFormatter\NumberFormatter::__construct() method's argument $style value 0 behavior is not implemented. The available styles are: CURRENCY, DECIMAL..  Please install the "intl" extension for full localization capabilities. (View: /var/www/seat/vendor/eveseat/web/src/resources/views/character/assets.blade.php)' in /var/www/seat/vendor/symfony/intl/NumberFormatter/NumberFormatter.php:292
Stack trace:
#0 /var/www/seat/bootstrap/cache/compiled.php(14631): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Intl\Exception\MethodArgumentValueNotImplementedException), 1)
#1 /var/www/seat/bootstrap/cache/compiled.php(14665): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/seat/s...', Array)
#2 /var/www/seat/bootstrap/cache/compiled.php(14498): Illuminate\View\Engines\CompilerEngine->get('/var/www/seat/v...', Array)
#3 /var/www/seat/bootstrap/cache/compiled.php(14486): Illuminate\View\View->getContents()
#4 /var/www/seat/bootstrap/cache/compiled.php(14477): Illuminate\View\View->renderContents()
#5 /var/www/seat/bootstrap/cache/compiled.php(15626): Illuminate\View\View->render()
#6 /var/www/seat/bootstrap/cache/compiled.php(15141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /var/www/seat/bootstrap/cache/compiled.php(7695): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /var/www/seat/bootstrap/cache/compiled.php(8922): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/seat/bootstrap/cache/compiled.php(9592): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/seat/bootstrap/cache/compiled.php(9574): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /var/www/seat/bootstrap/cache/compiled.php(8923): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /var/www/seat/bootstrap/cache/compiled.php(8908): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Seat\Web\Http\Controllers\Character\ViewController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'getAssets')
#15 /var/www/seat/bootstrap/cache/compiled.php(7862): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Seat\\Web\\Http\\C...', 'getAssets')
#16 /var/www/seat/bootstrap/cache/compiled.php(7833): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#17 /var/www/seat/bootstrap/cache/compiled.php(7486): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/seat/bootstrap/cache/compiled.php(9592): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/CharacterBouncer.php(69): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 [internal function]: Seat\Web\Http\Middleware\CharacterBouncer->handle(Object(Illuminate\Http\Request), Object(Closure), 'assets')
#22 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#23 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/Authenticate.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: Seat\Web\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/seat/bootstrap/cache/compiled.php(9574): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /var/www/seat/bootstrap/cache/compiled.php(7487): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 /var/www/seat/bootstrap/cache/compiled.php(7475): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#30 /var/www/seat/bootstrap/cache/compiled.php(7460): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#31 /var/www/seat/bootstrap/cache/compiled.php(2307): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/seat/bootstrap/cache/compiled.php(9592): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#34 /var/www/seat/bootstrap/cache/compiled.php(2925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#37 /var/www/seat/bootstrap/cache/compiled.php(12952): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#40 /var/www/seat/bootstrap/cache/compiled.php(11549): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#43 /var/www/seat/bootstrap/cache/compiled.php(12689): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#46 /var/www/seat/bootstrap/cache/compiled.php(12626): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#49 /var/www/seat/bootstrap/cache/compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /var/www/seat/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#52 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/seat/bootstrap/cache/compiled.php(9574): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#54 /var/www/seat/bootstrap/cache/compiled.php(2254): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#55 /var/www/seat/bootstrap/cache/compiled.php(2237): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#56 /var/www/seat/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#57 {main}  
```

**Comment by leonjza** [comment]
Can you check that you have the `php-intl` package installed for your distro?

**Comment by l0ser140** [comment]
`php-intl` was not installed in my distro. Installing solved problem.
