### ISSUE TITLE
Jobs stuck with ReflectionException

### ISSUE THREAD

**Issue by l0ser140** [eveseat/seat#22]
I have few jobs which are not working and just stuck in query.

Created | Owner ID | Api | Scope | Status
------|-----------------------|--------|-------------|-------
41 minutes ago | 0 | Server | Server | Queued
32 minutes ago | 4910363 | Corporation | Eve | Queued

In the same time various ReflectionException appear in the logs.

```
[2015-12-23 18:30:10] local.ERROR: exception 'ReflectionException' with message 'Class \Seat\EveQueues\Partial\CorporationWallet does not exist' in /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
Stack trace:
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(741): ReflectionClass->__construct('\\Seat\\EveQueues...')
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('\\Seat\\EveQueues...', Array)
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('\\Seat\\EveQueues...', Array)
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(153): Illuminate\Foundation\Application->make('\\Seat\\EveQueues...')
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(127): Illuminate\Queue\Jobs\Job->resolve('\\Seat\\EveQueues...')
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/RedisJob.php(50): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(208): Illuminate\Queue\Jobs\RedisJob->fire()
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), '10', '0')
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(109): Illuminate\Queue\Worker->pop('', 'high,medium,low...', '0', '3', '10')
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(71): Illuminate\Queue\Console\WorkCommand->runWorker('', 'high,medium,low...', '0', '128', false)
#10 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#13 /var/www/seat/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/seat/vendor/symfony/console/Application.php(838): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/seat/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/seat/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/seat/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main}  
```
```
[2015-12-23 19:00:29] local.ERROR: exception 'ReflectionException' with message 'Class \Seat\EveQueues\Full\Character does not exist' in /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
```

**Comment by leonjza** [comment]
Please give us full details of you environment. OS versions, PHP versions etc. Also the output of ` php artisan seat:version` and `sudo -u apache php artisan seat:admin:diagnose` where `apache` is the user the jobs are running as.

Lastly, can you try running `composer dump-autoload`, clear all jobs from the queue and check if the problem persists?

**Comment by l0ser140** [comment]
```
$ cat /proc/version 
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09)
```
```
$ php -v
PHP 5.6.14-0+deb8u1 (cli) (built: Oct  4 2015 16:13:10)
```
```
$ sudo -u www-data php artisan seat:admin:diagnose
SeAT Diagnostics
If you are not already doing so, it is recommended that you run this as the user the workers are running as.
Eg:
    sudo -u apache php artisan seat:admin:diagnose
This helps to check whether the permissions are correct.

 * Checking DEBUG mode
Debug mode disabled

 * Checking storage
/var/www/seat/storage is writable
/var/www/seat/storage/app/pheal/ is writable
/var/www/seat/storage/sde/ is writable
/var/www/seat/storage/logs/laravel.log is writable

 * Checking Database
+------------+------------------+
| Setting    | Value            |
+------------+------------------+
| Connection |                  |
| Host       | localhost        |
| Database   | seat             |
| Username   | seat             |
| Password   | **************** |
+------------+------------------+
Connection OK to database: seat

 * Checking Redis
+----------+-----------+
| Setting  | Value     |
+----------+-----------+
| Host     | 127.0.0.1 |
| Port     | 6379      |
| Database | 0         |
+----------+-----------+
Connected to Redis
Set random key of: 3rPKmRNUxm55e2TTWOBes6rSJ74B4DWsz9rfUtZRZfy3JZEAvHb5psJKthmcPJ5g
Set key to expire in 10 sec
Read key OK

 * Checking Pheal EVE API Access
Server Online: True
Online Players: 29172

SeAT Diagnostics complete
```

**Comment by leonjza** [comment]
Ok the web package can be upgraded. Does the `dump-autoload` help?

```
php artisan seat:version                                                                                                                                                     │································
[x] SeAT Package Versions                                                                                                                                                         │································
+---------------+---------+                                                                                                                                                       │································
| Package Name  | Version |                                                                                                                                                       │································
+---------------+---------+                                                                                                                                                       │································
| Api           | 1.0.4   |                                                                                                                                                       │································
| Console       | 1.0.6   |                                                                                                                                                       │································
| Eveapi        | 1.0.5   |                                                                                                                                                       │································
| Notifications | 1.0.2   |                                                                                                                                                       │································
| Web           | 1.0.11  |                                                                                                                                                       │································
| Services      | 1.0.7   |                                                                                                                                                       │································
+---------------+---------+       
```

**Comment by warlof** [comment]
Did you run an old 0.x SeAT installation ?
Those jobs seems to not be relevant from 1.x stuff and both version aren't compatible.

**Comment by l0ser140** [comment]
Yes, i have running 0.x seat in separate directory and problem definitely because of this.
Do you have any idea how to get them both working?

**Comment by leonjza** [comment]
Running multiple instances is not officially supported. Your best bet will be to hop onto slack/irc and talk to someone.

**Comment by warlof** [comment]
You need to run them in two separated directory and adding an extra redis service which will handle the second seat setup request.

You'll need to tweak seat 1.x a little bit in order to tell it which redis service it should use. If I remember right, it's already done with 0.x : https://github.com/eve-seat/seat/blob/master/app/config/env-sample.php
