### ISSUE TITLE
all my jobs fail: FileStorage.php @ line 178

### ISSUE THREAD

**Issue by sergiorochalopes** [eveseat/seat#229]
Seat Admin Diag reveals no issues and all versions are updated to latest.

Example of the full stack trace for one of them below (all my jobs have this error):

```
Job ID
00lVR4B0fTcadqu2cKVbqd5H5MafFPDx
Api
Scheduler
Scope
Key
Status
Error
Last Updater: Started APIKeyInfo Update

Exception       : Exception
Error Code      : 0
Error Message   : String could not be parsed as XML
File            : /var/www/seat/vendor/3rdpartyeve/phealng/lib/Pheal/Cache/FileStorage.php
Line            : 178

Traceback: 
#0 /var/www/seat/vendor/3rdpartyeve/phealng/lib/Pheal/Cache/FileStorage.php(178): SimpleXMLElement->__construct('')
#1 /var/www/seat/vendor/3rdpartyeve/phealng/lib/Pheal/Cache/FileStorage.php(158): Pheal\Cache\FileStorage->validateCache('')
#2 /var/www/seat/vendor/3rdpartyeve/phealng/lib/Pheal/Pheal.php(233): Pheal\Cache\FileStorage->load(5809468, 'S83ii5118endniN...', 'account', 'APIKeyInfo', Array)
#3 /var/www/seat/vendor/3rdpartyeve/phealng/lib/Pheal/Pheal.php(110): Pheal\Pheal->requestXml('account', 'APIKeyInfo', Array)
#4 /var/www/seat/vendor/eveseat/eveapi/src/Api/Account/APIKeyInfo.php(45): Pheal\Pheal->__call('APIKeyInfo', Array)
#5 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/CheckAndQueueKey.php(66): Seat\Eveapi\Api\Account\APIKeyInfo->call()
#6 [internal function]: Seat\Eveapi\Jobs\CheckAndQueueKey->handle()
#7 /var/www/seat/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#8 /var/www/seat/bootstrap/cache/compiled.php(9961): Illuminate\Container\Container->call(Array)
#9 /var/www/seat/bootstrap/cache/compiled.php(10076): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\CheckAndQueueKey))
#10 /var/www/seat/bootstrap/cache/compiled.php(10054): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\CheckAndQueueKey))
#11 /var/www/seat/bootstrap/cache/compiled.php(9964): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(47): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\CheckAndQueueKey), false)
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(73): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(203): Illuminate\Queue\Jobs\Job->fire()
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(153): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(75): Illuminate\Queue\Worker->runNextJob('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(84): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high,medium,low...')
#19 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#20 /var/www/seat/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#22 /var/www/seat/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/seat/vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/seat/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/seat/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/seat/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 {main}
```

**Comment by warlof** [comment]
Hello,

It may happened with corrupted cache.
Clear your cache using `sudo php artisan seat:cache:clear --include-pheal` (be sure to run the command in root SeAT installation folder ;)

**Comment by sergiorochalopes** [comment]
Seems like that fixed it!
Thank you :-)
