### ISSUE TITLE
Update corp and bookmarks fails

### ISSUE THREAD

**Issue by MyUncleSam** [eveseat/seat#238]
* **Problem**: checking corp keys is not working (some other updates produce that too but by disabling bookmark fetch I could "fix" it
* **Expected**: -
* **Logs / Screenshots / Proof**: (see below)
* **Version Info**: Ubuntun 16.04, Apache2, 7.0.28-1+ubuntu16.04.1+deb.sury.org+1

Error log:
```
Last Updater: Processing: Locations

Exception       : Illuminate\Database\QueryException
Error Code      : 42S02
Error Message   : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ep_seat.mapDenormalize' doesn't exist (SQL: select * from `mapDenormalize` where `solarSystemID` = 30001665 and `itemName` is not null and `groupID` in (6, 7, 8, 9, 10))
File            : /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php
Line            : 770

Traceback: 
#0 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(726): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(351): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1648): Illuminate\Database\Connection->select('select * from `...', Array, true)
#3 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1634): Illuminate\Database\Query\Builder->runSelect()
#4 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/eveseat/eveapi/src/Traits/Utils.php(108): Illuminate\Database\Query\Builder->get()
#5 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/eveseat/eveapi/src/Api/Corporation/Locations.php(88): Seat\Eveapi\Api\Corporation\Locations->find_nearest_celestial(30001665, '-823510059695.7...', '132485429324.31...', '1371470661902.3...')
#6 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/eveseat/eveapi/src/Jobs/UpdateAuthenticated.php(78): Seat\Eveapi\Api\Corporation\Locations->call()
#7 [internal function]: Seat\Eveapi\Jobs\UpdateAuthenticated->handle()
#8 /var/www/virtual/domain.tld/seat/htdocs/seat/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#9 /var/www/virtual/domain.tld/seat/htdocs/seat/bootstrap/cache/compiled.php(9961): Illuminate\Container\Container->call(Array)
#10 /var/www/virtual/domain.tld/seat/htdocs/seat/bootstrap/cache/compiled.php(10076): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#11 /var/www/virtual/domain.tld/seat/htdocs/seat/bootstrap/cache/compiled.php(10054): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#12 /var/www/virtual/domain.tld/seat/htdocs/seat/bootstrap/cache/compiled.php(9964): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(47): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\UpdateAuthenticated), false)
#14 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(73): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#15 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(203): Illuminate\Queue\Jobs\Job->fire()
#16 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(153): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#17 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(75): Illuminate\Queue\Worker->runNextJob('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#18 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#19 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(84): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high,medium,low...')
#20 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#21 /var/www/virtual/domain.tld/seat/htdocs/seat/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#22 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#23 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/virtual/domain.tld/seat/htdocs/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/virtual/domain.tld/seat/htdocs/seat/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 {main}
```

**Comment by MyUncleSam** [comment]
Found the problem. If you follow the instruction and execute `php artisan eve:update-sde -n` it is saying that it already exists. I added `--force` which executed it and created the missing tables.

Maybe you have to modify the documentation for installation?

**Comment by leonjza** [comment]
Thanks for the report! I think the real question here is how come the SDE was considered installed when the tables clearly did not exist? I am unsure what would cause this situation to happen other than manually dropping those tables. A fresh install should install / update the [sde](https://github.com/eveseat/installer/blob/master/src/Utils/Seat.php#L162) anyways.

**Comment by MyUncleSam** [comment]
Sorry for the delay, but this happened on a fresh installation. That is why I used `--force` to check if it is working then because it was not able to get worse 😄

**Comment by tohuw** [comment]
I ran into this issue today, @warlof and @MyUncleSam. I was able to fix it with `sudo -H -u www-data bash -c 'php /var/www/seat/artisan eve:update:sde --force'`, as suggested here. But I wonder why it happens?
