### ISSUE TITLE
3.X not able to update character properties

### ISSUE THREAD

**Issue by SNIPER722** [eveseat/seat#274]
* **Problem**:  unable to update character properties after init registration 
* **Expected**:  after each init login/register the update character job (everyhour) unable to update character properties, create a ton of failed job each hour
* **Version Info**:  3.0.0-beta3
* **Logs / Screenshots / Proof**:  

```
> Seat\Eseye\Exceptions\RequestFailedException in /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php:235
Stack trace:
#0 /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php(168): Seat\Eseye\Fetchers\GuzzleFetcher->httpRequest('post', 'https://login.e...', Array)
#1 /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php(148): Seat\Eseye\Fetchers\GuzzleFetcher->refreshToken()
#2 /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php(99): Seat\Eseye\Fetchers\GuzzleFetcher->getToken()
#3 /var/www/seat/vendor/eveseat/eseye/src/Eseye.php(445): Seat\Eseye\Fetchers\GuzzleFetcher->call('get', 'https://esi.tec...', Array)
#4 /var/www/seat/vendor/eveseat/eseye/src/Eseye.php(253): Seat\Eseye\Eseye->rawFetch('get', 'https://esi.tec...', Array)
#5 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/EsiBase.php(253): Seat\Eseye\Eseye->invoke('get', Object(GuzzleHttp\Psr7\Uri), Array)
#6 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Wallet/Character/Transactions.php(84): Seat\Eveapi\Jobs\EsiBase->retrieve(Array)
#7 [internal function]: Seat\Eveapi\Jobs\Wallet\Character\Transactions->handle()
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\Wallet\Character\Transactions))
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Wallet\Character\Transactions))
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\Wallet\Character\Transactions), false)
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#23 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#29 /var/www/seat/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#31 /var/www/seat/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/seat/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 {main}
```

**Comment by leonjza** [comment]
The actual error is missing in the stack trace. Could you paste that bit too please?

**Comment by Swizeve** [comment]
Also seeing something similar here, slightly different error but from the same php file.

Also seeing this for corps

```
(Seat\Eveapi\Jobs\Assets\Corporation\Locations
ID
4962
Queue
default
Tags
corporation, assets, locations, character_id:9999999
Failed At
18-05-01 18:20:27
Error
Seat\Eseye\Exceptions\RequestFailedException: Undefined 404 response. Original message: Invalid IDs in the request in /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php:235Stack trace:#0 /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php(102): Seat\Eseye\Fetchers\GuzzleFetcher->httpRequest('post', 'https://esi.tec...', Array, '[1021634432373]')#1 /var/www/seat/vendor/eveseat/eseye/src/Eseye.php(445): Seat\Eseye\Fetchers\GuzzleFetcher->call('post', 'https://esi.tec...', Array)#2 /var/www/seat/vendor/eveseat/eseye/src/Eseye.php(253): Seat\Eseye\Eseye->rawFetch('post', 'https://esi.tec...', Array)#3 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/EsiBase.php(253): Seat\Eseye\Eseye->invoke('post', Object(GuzzleHttp\Psr7\Uri), Array)#4 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Assets/Corporation/Locations.php(153): Seat\Eveapi\Jobs\EsiBase->retrieve(Array)#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(39): Seat\Eveapi\Jobs\Assets\Corporation\Locations->Seat\Eveapi\Jobs\Assets\Corporation\{closure}(Object(Illuminate\Database\Eloquent\Collection), 1)#6 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Assets/Corporation/Locations.php(181): Illuminate\Database\Eloquent\Builder->chunk(1000, Object(Closure))#7 [internal function]: Seat\Eveapi\Jobs\Assets\Corporation\Locations->handle()#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\Assets\Corporation\Locations))#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Assets\Corporation\Locations))#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\Assets\Corporation\Locations), false)#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high,medium,low...')#23 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)#29 /var/www/seat/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))#31 /var/www/seat/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#32 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#33 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#36 /var/www/seat/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#37 {main})
```

**Comment by leonjza** [comment]
:ccp:

**Comment by SNIPER722** [comment]
this is the full stack track from the horizon failed page and in the log. 
here is the data attached in a similar log

` {
  "method": "get",
  "endpoint": "/characters/{character_id}/wallet/transactions/",
  "version": "v1",
  "scope": "esi-wallet.read_character_wallet.v1",
  "tags": [
    "character",
    "wallet",
    "transactions"
  ],
  "from_id": 9223372036854776000,
  "tries": 1,
  "roles": [],
  "page": null,
  "request_body": [],
  "query_string": [],
  "token": {
    "class": "Seat\\Eveapi\\Models\\RefreshToken",
    "id": 2113014515,
    "connection": "mysql"
  },
  "client": null,
  "public_call": null,
  "job": null,
  "connection": null,
  "queue": null,
  "chainConnection": null,
  "chainQueue": null,
  "delay": null,
  "chained": []
}`

**Comment by SNIPER722** [comment]
Believe this might related with a CCP issue. nothing is SeAT related.
