### ISSUE TITLE
v3: Market Prices fail to update

### ISSUE THREAD

**Issue by MrBMT** [eveseat/seat#278]
* **Problem**: Market Prices are failing to update
* **Expected**: Market Prices should update
* **Logs / Screenshots / Proof**: See Below
* **Version Info**: _PHP 7.1, SeAT 3.0.0-beta3, Debian 9_

```
Seat\Eveapi\Jobs\Market\Prices
ID 1789
Queue default
Tags public, market, prices
Failed At 18-05-01 22:47:54
Error
Illuminate\Queue\MaxAttemptsExceededException: Seat\Eveapi\Jobs\Market\Prices has been attempted too many times or run too long. The job may have previously timed out. in /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:394
Stack trace:
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\Queue\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts('redis', Object(Illuminate\Queue\Jobs\RedisJob), 1)
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#5 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#11 /var/www/seat/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#13 /var/www/seat/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/seat/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 {main}

Data
{
  "method": "get",
  "endpoint": "/markets/prices/",
  "version": "v1",
  "public_call": true,
  "tags": [
    "public",
    "market",
    "prices"
  ],
  "tries": 1,
  "scope": "public",
  "roles": [],
  "page": null,
  "request_body": [],
  "query_string": [],
  "token": null,
  "client": null,
  "job": null,
  "connection": null,
  "queue": null,
  "chainConnection": null,
  "chainQueue": null,
  "delay": null,
  "chained": []
}
```

**Comment by MrBMT** [comment]
@herpaderpaldent Possibly a silly question... but how do I get composer to download the non beta-tagged release? I've checked and I don't have those changes, but running composer update doesn't want to update those packages.

**Comment by herpaderpaldent** [comment]
you'd need to `git fetch` and `git pull` all of the packages inside your `your_docker_folder\seat\packages\eveseat`

**Comment by leonjza** [comment]
This was fixed and waiting for me to tag the next beta.

**Comment by MrBMT** [comment]
Brilliant, I've just updated to the latest version of everything again today and can confirm that it's now working. Closing this off. Thank you!
