### ISSUE TITLE
PDOException: SQLSTATE[23000] when getting most data

### ISSUE THREAD

**Issue by evileyecc1** [eveseat/seat#286]
* **Problem**: ``` Integrity constraint violation: 1062 Duplicate entry '610748534-1026484303056' for key 'PRIMARY' ``` when getting most data.Contracts,killmails,structures,wallet journal etc.
* **Expected**: Exists in db,but when call firstOrCreate.It create a new one.
* **Logs / Screenshots / Proof**: 
Payload
```
{"displayName":"Seat\\Eveapi\\Jobs\\Corporation\\Structures","job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":1,"timeout":null,"timeoutAt":null,"data":{"commandName":"Seat\\Eveapi\\Jobs\\Corporation\\Structures","command":"O:39:\"Seat\\Eveapi\\Jobs\\Corporation\\Structures\":21:{s:9:\"\u0000*\u0000method\";s:3:\"get\";s:11:\"\u0000*\u0000endpoint\";s:42:\"\/corporations\/{corporation_id}\/structures\/\";s:10:\"\u0000*\u0000version\";s:2:\"v2\";s:8:\"\u0000*\u0000scope\";s:35:\"esi-corporations.read_structures.v1\";s:8:\"\u0000*\u0000roles\";a:1:{i:0;s:15:\"Station_Manager\";}s:7:\"\u0000*\u0000tags\";a:2:{i:0;s:11:\"corporation\";i:1;s:10:\"structures\";}s:7:\"\u0000*\u0000page\";i:1;s:19:\"\u0000*\u0000known_structures\";O:29:\"Illuminate\\Support\\Collection\":1:{s:8:\"\u0000*\u0000items\";a:0:{}}s:5:\"tries\";i:1;s:15:\"\u0000*\u0000request_body\";a:0:{}s:15:\"\u0000*\u0000query_string\";a:0:{}s:8:\"\u0000*\u0000token\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":3:{s:5:\"class\";s:31:\"Seat\\Eveapi\\Models\\RefreshToken\";s:2:\"id\";i:90376911;s:10:\"connection\";s:5:\"mysql\";}s:9:\"\u0000*\u0000client\";N;s:14:\"\u0000*\u0000public_call\";N;s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}"},"id":"321686","attempts":0,"type":"job","tags":["corporation","structures","character_id:90376911"],"pushedAt":1525455405}
```
Stack trace:https://pastebin.com/zZfWVWTY
* **Version Info**: 
PHP 7.1
SeAT dev-master
OS Ubuntu16.04

**Comment by evileyecc1** [comment]
Corporation KM stack track:
```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '67934463' for key 'PRIMARY' in /home/wwwroot/version_3.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:141
Stack trace:
#0 /home/wwwroot/version_3.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(141): PDOStatement->execute(NULL)
#1 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(458): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `ki...', Array)
#3 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into `ki...', Array, Object(Closure))
#4 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\Database\Connection->run('insert into `ki...', Array, Object(Closure))
#5 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\Database\Connection->statement('insert into `ki...', Array)
#6 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2142): Illuminate\Database\Connection->insert('insert into `ki...', Array)
#7 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1285): Illuminate\Database\Query\Builder->insert(Array)
#8 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(698): Illuminate\Database\Eloquent\Builder->__call('insert', Array)
#9 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(550): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#10 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(384): Illuminate\Database\Eloquent\Model->save()
#11 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1038): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(Seat\Eveapi\Models\Killmails\KillmailVictim))
#12 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(385): tap(Object(Seat\Eveapi\Models\Killmails\KillmailVictim), Object(Closure))
#13 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1470): Illuminate\Database\Eloquent\Builder->firstOrCreate(Array)
#14 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1482): Illuminate\Database\Eloquent\Model->__call('firstOrCreate', Array)
#15 /home/wwwroot/version_3.0/packages/eveapi/src/Jobs/Killmails/Corporation/Detail.php(100): Illuminate\Database\Eloquent\Model::__callStatic('firstOrCreate', Array)
#16 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\Killmails\Corporation\Detail->Seat\Eveapi\Jobs\Killmails\Corporation\{closure}(67934463, 'a3b10cd14dc5bc7...')
#17 /home/wwwroot/version_3.0/packages/eveapi/src/Jobs/Killmails/Corporation/Detail.php(145): Illuminate\Support\Collection->each(Object(Closure))
#18 [internal function]: Seat\Eveapi\Jobs\Killmails\Corporation\Detail->handle()
#19 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#20 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#21 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#22 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#23 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#24 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\Killmails\Corporation\Detail))
#25 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Killmails\Corporation\Detail))
#26 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\Killmails\Corporation\Detail), false)
#28 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#29 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#30 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#31 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#32 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'killmails', Object(Illuminate\Queue\WorkerOptions))
#33 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'killmails')
#34 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#35 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#36 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#37 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#38 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#39 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#40 /home/wwwroot/version_3.0/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#41 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#42 /home/wwwroot/version_3.0/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /home/wwwroot/version_3.0/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /home/wwwroot/version_3.0/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 /home/wwwroot/version_3.0/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#48 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '67934463' for key 'PRIMARY' in /home/wwwroot/version_3.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:143
Stack trace:
#0 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(458): Doctrine\DBAL\Driver\PDOStatement->execute()
#1 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `ki...', Array)
#2 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into `ki...', Array, Object(Closure))
#3 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\Database\Connection->run('insert into `ki...', Array, Object(Closure))
#4 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\Database\Connection->statement('insert into `ki...', Array)
#5 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2142): Illuminate\Database\Connection->insert('insert into `ki...', Array)
#6 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1285): Illuminate\Database\Query\Builder->insert(Array)
#7 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(698): Illuminate\Database\Eloquent\Builder->__call('insert', Array)
#8 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(550): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#9 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(384): Illuminate\Database\Eloquent\Model->save()
#10 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1038): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(Seat\Eveapi\Models\Killmails\KillmailVictim))
#11 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(385): tap(Object(Seat\Eveapi\Models\Killmails\KillmailVictim), Object(Closure))
#12 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1470): Illuminate\Database\Eloquent\Builder->firstOrCreate(Array)
#13 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1482): Illuminate\Database\Eloquent\Model->__call('firstOrCreate', Array)
#14 /home/wwwroot/version_3.0/packages/eveapi/src/Jobs/Killmails/Corporation/Detail.php(100): Illuminate\Database\Eloquent\Model::__callStatic('firstOrCreate', Array)
#15 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\Killmails\Corporation\Detail->Seat\Eveapi\Jobs\Killmails\Corporation\{closure}(67934463, 'a3b10cd14dc5bc7...')
#16 /home/wwwroot/version_3.0/packages/eveapi/src/Jobs/Killmails/Corporation/Detail.php(145): Illuminate\Support\Collection->each(Object(Closure))
#17 [internal function]: Seat\Eveapi\Jobs\Killmails\Corporation\Detail->handle()
#18 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#19 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#21 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#22 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#23 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\Killmails\Corporation\Detail))
#24 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Killmails\Corporation\Detail))
#25 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\Killmails\Corporation\Detail), false)
#27 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#28 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#29 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#30 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#31 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'killmails', Object(Illuminate\Queue\WorkerOptions))
#32 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'killmails')
#33 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#34 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#35 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#36 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#37 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#38 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#39 /home/wwwroot/version_3.0/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#40 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#41 /home/wwwroot/version_3.0/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /home/wwwroot/version_3.0/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /home/wwwroot/version_3.0/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /home/wwwroot/version_3.0/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 {main}

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '67934463' for key 'PRIMARY' (SQL: insert into `killmail_victims` (`killmail_id`, `character_id`, `corporation_id`, `alliance_id`, `faction_id`, `damage_taken`, `ship_type_id`, `x`, `y`, `z`, `updated_at`, `created_at`) values (67934463, 1753019545, 98120016, 99003581, , 5349, 22456, -16043708308.267, -2685816327.832, -31763067027.112, 2018-05-05 18:33:26, 2018-05-05 18:33:26)) in /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
Stack trace:
#0 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into `ki...', Array, Object(Closure))
#1 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\Database\Connection->run('insert into `ki...', Array, Object(Closure))
#2 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\Database\Connection->statement('insert into `ki...', Array)
#3 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2142): Illuminate\Database\Connection->insert('insert into `ki...', Array)
#4 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1285): Illuminate\Database\Query\Builder->insert(Array)
#5 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(698): Illuminate\Database\Eloquent\Builder->__call('insert', Array)
#6 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(550): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#7 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(384): Illuminate\Database\Eloquent\Model->save()
#8 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1038): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(Seat\Eveapi\Models\Killmails\KillmailVictim))
#9 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(385): tap(Object(Seat\Eveapi\Models\Killmails\KillmailVictim), Object(Closure))
#10 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1470): Illuminate\Database\Eloquent\Builder->firstOrCreate(Array)
#11 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1482): Illuminate\Database\Eloquent\Model->__call('firstOrCreate', Array)
#12 /home/wwwroot/version_3.0/packages/eveapi/src/Jobs/Killmails/Corporation/Detail.php(100): Illuminate\Database\Eloquent\Model::__callStatic('firstOrCreate', Array)
#13 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\Killmails\Corporation\Detail->Seat\Eveapi\Jobs\Killmails\Corporation\{closure}(67934463, 'a3b10cd14dc5bc7...')
#14 /home/wwwroot/version_3.0/packages/eveapi/src/Jobs/Killmails/Corporation/Detail.php(145): Illuminate\Support\Collection->each(Object(Closure))
#15 [internal function]: Seat\Eveapi\Jobs\Killmails\Corporation\Detail->handle()
#16 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#17 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#18 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#19 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#20 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#21 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\Killmails\Corporation\Detail))
#22 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Killmails\Corporation\Detail))
#23 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\Killmails\Corporation\Detail), false)
#25 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#26 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#27 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#28 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#29 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'killmails', Object(Illuminate\Queue\WorkerOptions))
#30 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'killmails')
#31 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#32 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#33 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#34 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#35 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#36 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#37 /home/wwwroot/version_3.0/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#38 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#39 /home/wwwroot/version_3.0/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /home/wwwroot/version_3.0/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 /home/wwwroot/version_3.0/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /home/wwwroot/version_3.0/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /home/wwwroot/version_3.0/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 {main}
```

**Comment by Swizeve** [comment]
Also getting this, is the only regularly failing job type for me now.

Seat\Eveapi\Jobs\Universe\Structures
ID 44474
Queue default
Tags character, universe, structures, character_id:number
Failed At 18-05-11 20:08:45

**Stack trace:** https://pastebin.com/D1jha7iL

**Comment by warlof** [comment]
@swizeve @evileyecc1 since released version,  do you still have such issue or the ticket can be close?
