### ISSUE TITLE
Whoops, looks like something went wrong. FatalThrowableError Parse error: syntax error, unexpected '?'

### ISSUE THREAD

**Issue by D0N2k** [eveseat/seat#290]
Hey,

I installed seat 3.0 with the new documentation on our ubuntu server. Everything worked fine. But now when I want to load the seat webpage it says: Whoops, looks like something went wrong. 

![home](https://user-images.githubusercontent.com/38753864/39819346-8118a904-53a3-11e8-9a58-93adf6cecc89.png)

`su - www-data -s /bin/bash -c 'php /var/customers/webs/seat/artisan seat:admin:diagnose'`

Output is:
``` * Getting environment information
Current User: www-data
PHP Version: 7.1.17-1+ubuntu16.04.1+deb.sury.org+1
Host OS: Linux  4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64
SeAT Basepath: /var/customers/webs/seat

 * Checking DEBUG mode
Debug mode is enabled. This is not recommended in production!

 * Checking storage
/var/customers/webs/seat/storage is writable
/var/customers/webs/seat/storage/logs is writable
/var/customers/webs/seat/storage/eseye is writable
/var/customers/webs/seat/storage/sde/ is writable
/var/customers/webs/seat/storage/logs/laravel.log is not writable

 * Checking Database
+------------+---------------------+
| Setting    | Value               |
+------------+---------------------+
| Connection | mysql               |
| Host       | 127.0.0.1           |
| Database   | seat                |
| Username   | root                |
| Password   | ******************* |
+------------+---------------------+
Connection OK to database: seat

 * Checking Redis
+----------+-----------+
| Setting  | Value     |
+----------+-----------+
| Host     | 127.0.0.1 |
| Port     | 6379      |
| Database | 0         |
+----------+-----------+
Connected to Redis
Set random key of: oXZj0YGgEFBFNXRrYiEVa5fO8972R5K5EYfWjXjlPtamPhAZK0qYJSJ59LYLb3QF
Set key to expire in 10 sec
Read key OK

 * Checking ESI Access
Server Online Since: 2018-05-09T11:05:28Z
Online Players: 23684
ESI appears to be OK

Checking Local and Github Versions. Please wait...
+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 3.0.0-beta5   | 2.0.10        |
| Console       | 3.0.0-beta3   | 2.0.4         |
| Eveapi        | 3.0.0-beta8   | 2.0.14        |
| Notifications | 3.0.0-beta2   | 2.0.11        |
| Web           | 3.0.0-beta7   | 2.0.19        |
| Services      | 3.0.0-beta6   | 2.0.13        |
+---------------+---------------+---------------+
SeAT Diagnostics complete
```
```
Laravel Log says:
[2018-05-09 14:02:32] local.ERROR: Parse error: syntax error, unexpected '?' {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Parse error: syntax error, unexpected '?' at /var/customers/webs/seat/vendor/eveseat/services/src/Repositories/Seat/S$
[stacktrace]
#0 /var/customers/webs/seat/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/var/customers/...')
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Seat\\\\Services\\\\R...')
#2 /var/customers/webs/seat/vendor/eveseat/web/src/Http/Controllers/HomeController.php(37): spl_autoload_call('Seat\\\\Services\\\\R...')
#3 /var/customers/webs/seat/vendor/composer/ClassLoader.php(444): include('/var/customers/...')
#4 /var/customers/webs/seat/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/var/customers/...')
#5 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Seat\\\\Web\\\\Http\\\\C...')
#6 [internal function]: spl_autoload_call('Seat\\\\Web\\\\Http\\\\C...')
#7 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('Seat\\\\Web\\\\Http\\\\C...')
#8 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build('Seat\\\\Web\\\\Http\\\\C...')
#9 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve('Seat\\\\Web\\\\Http\\\\C...', Array)
#10 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\\Container\\Container->make('Seat\\\\Web\\\\Http\\\\C...', Array)
#11 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(226): Illuminate\\Foundation\\Application->make('Seat\\\\Web\\\\Http\\\\C...')
#12 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(796): Illuminate\\Routing\\Route->getController()
#13 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(757): Illuminate\\Routing\\Route->controllerMiddleware()
#14 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(671): Illuminate\\Routing\\Route->gatherMiddleware()
#15 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#16 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#17 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#18 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#19 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#20 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/customers/webs/seat/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#38 /var/customers/webs/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#39 /var/customers/webs/seat/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#40 {main}
"}
```

Apache/2.4.33 (Ubuntu)
Thanks

**Comment by D0N2k** [comment]
Hey,

next to php7.1 i got 7.0 and 7.2 installed. but 7.1 should be default with `update-alternatives`.

php -i says php version 7.1.17-1

**Comment by herpaderpaldent** [comment]
`/var/customers/webs/seat/storage/logs/laravel.log is not writable`

if you are using apache you need to realize www-data is not able to access the seat if he does not own it or have permission to RL from it
2 Solutions : 
1. set permission to 777 (unsecure) 
2. let virtual host run as the user own director (deafult seat)
Even better let SeAT run as docker

**Comment by D0N2k** [comment]
Hey,

```/var/customers/webs/seat/storage/logs# ls -la
insgesamt 160
drwxr-xr-x 2 www-data www-data   4096 Mai  9 16:15 .
drwxr-xr-x 7 www-data www-data   4096 Mai  9 15:06 ..
-rwxr-xr-x 1 www-data www-data   7336 Mai  9 18:50 eseye-2018-05-09.log
-rwxr-xr-x 1 www-data www-data     14 Mai  7 18:44 .gitignore
-rwxr-xr-x 1 www-data www-data 138054 Mai  9 16:02 laravel-2018-05-09.log
```

Permissions should be set correctly. Well I will try to install it with seat as owner.

**Comment by warlof** [comment]
@D0N2k which http service are you using ? apache ?
if so, ensure the apache mod is php7.1 and not one of 7.2 or 7.0

if using nginx, double check the used socket

**Comment by D0N2k** [comment]
Nevermind php -i showed version 7.1 but ran on 7.0 a2dismod helped.

thanks

**Comment by warlof** [comment]
you're welcome :)

**Comment by herpaderpaldent** [comment]
You may want to close this issue @D0N2k  if it is solved
