### ISSUE TITLE
Base table or view not found: 1146 Table 'seat.corporation_industry_mining_observer_datas' doesn't exist

### ISSUE THREAD

**Issue by MrBMT** [eveseat/seat#291]
* **Problem**: _It seems corporation_industry_mining_observer_datas is being referenced, when the actual table created is corporation_industry_mining_observer_data (Note: No s on the end)_
* **Logs / Screenshots / Proof**: _See below_
* **Version Info**: _PHP 7.1, Debian 9_
```
+---------------+---------------+
| Package Name  | Local Version |
+---------------+---------------+
| Api           | 3.0.0-beta5   |
| Console       | 3.0.0-beta3   |
| Eveapi        | 3.0.0-beta8   |
| Notifications | 3.0.0-beta2   |
| Web           | 3.0.0-beta7   |
| Services      | 3.0.0-beta6   |
+---------------+---------------+
```

```
Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails
ID 573885
Queue default
Tags corporation, mining, observers, details, character_id:<removed>
Failed At 18-05-09 15:05:10

Error
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'seat.corporation_industry_mining_observer_datas' doesn't exist in /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80
Stack trace:
#0 /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(80): PDO->prepare('select * from `...', Array)
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Doctrine\DBAL\Driver\PDOConnection->prepare('select * from `...')
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from `...', Array)
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1719): Illuminate\Database\Connection->select('select * from `...', Array, true)
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1704): Illuminate\Database\Query\Builder->runSelect()
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(483): Illuminate\Database\Query\Builder->get(Array)
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(467): Illuminate\Database\Eloquent\Builder->getModels(Array)
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\Database\Eloquent\Builder->get(Array)
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(363): Illuminate\Database\Eloquent\Builder->first()
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1470): Illuminate\Database\Eloquent\Builder->firstOrNew(Array)
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1482): Illuminate\Database\Eloquent\Model->__call('firstOrNew', Array)
#13 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Industry/Corporation/Mining/ObserverDetails.php(101): Illuminate\Database\Eloquent\Model::__callStatic('firstOrNew', Array)
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails->Seat\Eveapi\Jobs\Industry\Corporation\Mining\{closure}(Object(stdClass), 0)
#15 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Industry/Corporation/Mining/ObserverDetails.php(107): Illuminate\Support\Collection->each(Object(Closure))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails->Seat\Eveapi\Jobs\Industry\Corporation\Mining\{closure}(Object(Seat\Eveapi\Models\Industry\CorporationIndustryMiningObserver), 3)
#17 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Industry/Corporation/Mining/ObserverDetails.php(115): Illuminate\Support\Collection->each(Object(Closure))
#18 [internal function]: Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails->handle()
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails))
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails))
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails), false)
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#34 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#37 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#39 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#40 /var/www/seat/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#41 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#42 /var/www/seat/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 /var/www/seat/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#48 {main}Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'seat.corporation_industry_mining_observer_datas' doesn't exist in /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82Stack trace:
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Doctrine\DBAL\Driver\PDOConnection->prepare('select * from `...')
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from `...', Array)
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1719): Illuminate\Database\Connection->select('select * from `...', Array, true)
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1704): Illuminate\Database\Query\Builder->runSelect()
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(483): Illuminate\Database\Query\Builder->get(Array)
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(467): Illuminate\Database\Eloquent\Builder->getModels(Array)
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\Database\Eloquent\Builder->get(Array)
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(363): Illuminate\Database\Eloquent\Builder->first()
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1470): Illuminate\Database\Eloquent\Builder->firstOrNew(Array)
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1482): Illuminate\Database\Eloquent\Model->__call('firstOrNew', Array)
#12 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Industry/Corporation/Mining/ObserverDetails.php(101): Illuminate\Database\Eloquent\Model::__callStatic('firstOrNew', Array)
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails->Seat\Eveapi\Jobs\Industry\Corporation\Mining\{closure}(Object(stdClass), 0)
#14 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Industry/Corporation/Mining/ObserverDetails.php(107): Illuminate\Support\Collection->each(Object(Closure))
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails->Seat\Eveapi\Jobs\Industry\Corporation\Mining\{closure}(Object(Seat\Eveapi\Models\Industry\CorporationIndustryMiningObserver), 3)
#16 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Industry/Corporation/Mining/ObserverDetails.php(115): Illuminate\Support\Collection->each(Object(Closure))
#17 [internal function]: Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails->handle()
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails))
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails), false)
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#33 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#37 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#39 /var/www/seat/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#40 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#41 /var/www/seat/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /var/www/seat/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 {main}Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'seat.corporation_industry_mining_observer_datas' doesn't exist (SQL: select * from `corporation_industry_mining_observer_datas` where (`corporation_id` = 98469412 and `observer_id` = 1026906902693 and `recorded_corporation_id` = 98469412 and `character_id` = 96283919 and `type_id` = 46300) limit 1) in /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664Stack trace:
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1719): Illuminate\Database\Connection->select('select * from `...', Array, true)
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1704): Illuminate\Database\Query\Builder->runSelect()
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(483): Illuminate\Database\Query\Builder->get(Array)
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(467): Illuminate\Database\Eloquent\Builder->getModels(Array)
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\Database\Eloquent\Builder->get(Array)
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(363): Illuminate\Database\Eloquent\Builder->first()
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1470): Illuminate\Database\Eloquent\Builder->firstOrNew(Array)
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1482): Illuminate\Database\Eloquent\Model->__call('firstOrNew', Array)
#10 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Industry/Corporation/Mining/ObserverDetails.php(101): Illuminate\Database\Eloquent\Model::__callStatic('firstOrNew', Array)
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails->Seat\Eveapi\Jobs\Industry\Corporation\Mining\{closure}(Object(stdClass), 0)
#12 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Industry/Corporation/Mining/ObserverDetails.php(107): Illuminate\Support\Collection->each(Object(Closure))
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails->Seat\Eveapi\Jobs\Industry\Corporation\Mining\{closure}(Object(Seat\Eveapi\Models\Industry\CorporationIndustryMiningObserver), 3)
#14 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Industry/Corporation/Mining/ObserverDetails.php(115): Illuminate\Support\Collection->each(Object(Closure))
#15 [internal function]: Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails->handle()
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails))
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails), false)
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#31 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#37 /var/www/seat/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#39 /var/www/seat/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /var/www/seat/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 {main}

Data
{
  "method": "get",
  "endpoint": "/corporation/{corporation_id}/mining/observers/{observer_id}/",
  "version": "v1",
  "scope": "esi-industry.read_corporation_mining.v1",
  "roles": [
    "Accountant"
  ],
  "tags": [
    "corporation",
    "mining",
    "observers",
    "details"
  ],
  "page": 1,
  "tries": 1,
  "request_body": [],
  "query_string": [],
  "token": {
    "class": "Seat\\Eveapi\\Models\\RefreshToken",
    "id": <removed>,
    "connection": "mysql"
  },
  "client": null,
  "public_call": null,
  "job": null,
  "connection": null,
  "queue": null,
  "chainConnection": null,
  "chainQueue": null,
  "delay": null,
  "chained": []
}
```

**Comment by MrBMT** [comment]
Fixed with the release of v3.0.0-beta9 🎉
