### ISSUE TITLE
Seat\Eveapi\Jobs\Contracts\Corporation\Items - Duplicate entry for key 'PRIMARY'

### ISSUE THREAD

**Issue by MrBMT** [eveseat/seat#297]
* **Problem**: _Hundreds of Duplicate entry errors for Corporation Contract Items_
![seat-errors](https://user-images.githubusercontent.com/6931281/39900642-131b249a-54bb-11e8-9f64-806c62f79df9.png)

* **Expected**: _Skip or update the contract items (whichever needed) if they already exist in DB_
* **Logs / Screenshots / Proof**: _See below_
* **Version Info**: _PHP 7.1, Debian 9_

```
+---------------+---------------+
| Package Name  | Local Version |
+---------------+---------------+
| Api           | 3.0.0-beta5   |
| Console       | 3.0.0-beta4   |
| Eveapi        | 3.0.0-beta9   |
| Notifications | 3.0.0-beta2   |
| Web           | 3.0.0-beta8   |
| Services      | 3.0.0-beta6   |
+---------------+---------------+
```

```
Seat\Eveapi\Jobs\Contracts\Corporation\Items
ID 723036
Queue default
Tags corporation, contracts, items, character_id:<removed>
Failed At 18-05-11 01:04:36
Error
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '131765097-2585424307' for key 'PRIMARY' in /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:141Stack trace:
#0 /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(141): PDOStatement->execute(NULL)
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(458): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `co...', Array)
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into `co...', Array, Object(Closure))
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\Database\Connection->run('insert into `co...', Array, Object(Closure))
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\Database\Connection->statement('insert into `co...', Array)
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2142): Illuminate\Database\Connection->insert('insert into `co...', Array)
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1285): Illuminate\Database\Query\Builder->insert(Array)
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(698): Illuminate\Database\Eloquent\Builder->__call('insert', Array)
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(550): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(384): Illuminate\Database\Eloquent\Model->save()
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1038): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(Seat\Eveapi\Models\Contracts\ContractItem))
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(385): tap(Object(Seat\Eveapi\Models\Contracts\ContractItem), Object(Closure))
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1470): Illuminate\Database\Eloquent\Builder->firstOrCreate(Array)
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1482): Illuminate\Database\Eloquent\Model->__call('firstOrCreate', Array)
#15 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Contracts/Corporation/Items.php(154): Illuminate\Database\Eloquent\Model::__callStatic('firstOrCreate', Array)
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\Contracts\Corporation\Items->Seat\Eveapi\Jobs\Contracts\Corporation\{closure}(Object(stdClass), 14)
#17 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Contracts/Corporation/Items.php(156): Illuminate\Support\Collection->each(Object(Closure))
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\Contracts\Corporation\Items->Seat\Eveapi\Jobs\Contracts\Corporation\{closure}(131765097, 9)
#19 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Contracts/Corporation/Items.php(183): Illuminate\Support\Collection->each(Object(Closure))
#20 [internal function]: Seat\Eveapi\Jobs\Contracts\Corporation\Items->handle()
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\Contracts\Corporation\Items))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Contracts\Corporation\Items))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\Contracts\Corporation\Items), false)
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#36 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#37 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#39 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#40 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#41 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#42 /var/www/seat/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#43 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#44 /var/www/seat/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#48 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#49 /var/www/seat/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#50 {main}Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '131765097-2585424307' for key 'PRIMARY' in /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:143Stack trace:
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(458): Doctrine\DBAL\Driver\PDOStatement->execute()
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `co...', Array)
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into `co...', Array, Object(Closure))
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\Database\Connection->run('insert into `co...', Array, Object(Closure))
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\Database\Connection->statement('insert into `co...', Array)
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2142): Illuminate\Database\Connection->insert('insert into `co...', Array)
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1285): Illuminate\Database\Query\Builder->insert(Array)
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(698): Illuminate\Database\Eloquent\Builder->__call('insert', Array)
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(550): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(384): Illuminate\Database\Eloquent\Model->save()
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1038): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(Seat\Eveapi\Models\Contracts\ContractItem))
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(385): tap(Object(Seat\Eveapi\Models\Contracts\ContractItem), Object(Closure))
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1470): Illuminate\Database\Eloquent\Builder->firstOrCreate(Array)
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1482): Illuminate\Database\Eloquent\Model->__call('firstOrCreate', Array)
#14 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Contracts/Corporation/Items.php(154): Illuminate\Database\Eloquent\Model::__callStatic('firstOrCreate', Array)
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\Contracts\Corporation\Items->Seat\Eveapi\Jobs\Contracts\Corporation\{closure}(Object(stdClass), 14)
#16 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Contracts/Corporation/Items.php(156): Illuminate\Support\Collection->each(Object(Closure))
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\Contracts\Corporation\Items->Seat\Eveapi\Jobs\Contracts\Corporation\{closure}(131765097, 9)
#18 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Contracts/Corporation/Items.php(183): Illuminate\Support\Collection->each(Object(Closure))
#19 [internal function]: Seat\Eveapi\Jobs\Contracts\Corporation\Items->handle()
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\Contracts\Corporation\Items))
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Contracts\Corporation\Items))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\Contracts\Corporation\Items), false)
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#35 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#37 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#39 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#40 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#41 /var/www/seat/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#42 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#43 /var/www/seat/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#48 /var/www/seat/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#49 {main}Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '131765097-2585424307' for key 'PRIMARY' (SQL: insert into `contract_items` (`contract_id`, `record_id`, `type_id`, `quantity`, `raw_quantity`, `is_singleton`, `is_included`, `updated_at`, `created_at`) values (131765097, 2585424307, 28668, 50, , 0, 1, 2018-05-11 00:04:37, 2018-05-11 00:04:37)) in /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664Stack trace:
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into `co...', Array, Object(Closure))
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\Database\Connection->run('insert into `co...', Array, Object(Closure))
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\Database\Connection->statement('insert into `co...', Array)
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2142): Illuminate\Database\Connection->insert('insert into `co...', Array)
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1285): Illuminate\Database\Query\Builder->insert(Array)
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(698): Illuminate\Database\Eloquent\Builder->__call('insert', Array)
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(550): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(384): Illuminate\Database\Eloquent\Model->save()
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1038): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(Seat\Eveapi\Models\Contracts\ContractItem))
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(385): tap(Object(Seat\Eveapi\Models\Contracts\ContractItem), Object(Closure))
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1470): Illuminate\Database\Eloquent\Builder->firstOrCreate(Array)
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1482): Illuminate\Database\Eloquent\Model->__call('firstOrCreate', Array)
#12 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Contracts/Corporation/Items.php(154): Illuminate\Database\Eloquent\Model::__callStatic('firstOrCreate', Array)
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\Contracts\Corporation\Items->Seat\Eveapi\Jobs\Contracts\Corporation\{closure}(Object(stdClass), 14)
#14 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Contracts/Corporation/Items.php(156): Illuminate\Support\Collection->each(Object(Closure))
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\Contracts\Corporation\Items->Seat\Eveapi\Jobs\Contracts\Corporation\{closure}(131765097, 9)
#16 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Contracts/Corporation/Items.php(183): Illuminate\Support\Collection->each(Object(Closure))
#17 [internal function]: Seat\Eveapi\Jobs\Contracts\Corporation\Items->handle()
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\Contracts\Corporation\Items))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Contracts\Corporation\Items))
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\Contracts\Corporation\Items), false)
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#33 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#37 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#39 /var/www/seat/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#40 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#41 /var/www/seat/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /var/www/seat/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 {main}
Data
{
  "method": "get",
  "endpoint": "/corporations/{corporation_id}/contracts/{contract_id}/items/",
  "version": "v1",
  "scope": "esi-contracts.read_corporation_contracts.v1",
  "tags": [
    "corporation",
    "contracts",
    "items"
  ],
  "iteration_count": 0,
  "cycle_start": {
    "date": "2018-05-11 00:00:03.198955",
    "timezone_type": 3,
    "timezone": "UTC"
  },
  "cycle_duration": 10,
  "max_cycle_requests": 20,
  "tries": 1,
  "roles": [],
  "page": null,
  "request_body": [],
  "query_string": [],
  "token": {
    "class": "Seat\\Eveapi\\Models\\RefreshToken",
    "id": <removed>,
    "connection": "mysql"
  },
  "client": null,
  "public_call": null,
  "job": null,
  "connection": null,
  "queue": null,
  "chainConnection": null,
  "chainQueue": null,
  "delay": null,
  "chained": [
    "O:43:\"Seat\\Eveapi\\Jobs\\Contracts\\Corporation\\Bids\":20:{s:9:\"\u0000*\u0000method\";s:3:\"get\";s:11:\"\u0000*\u0000endpoint\";s:60:\"/corporations/{corporation_id}/contracts/{contract_id}/bids/\";s:10:\"\u0000*\u0000version\";s:2:\"v1\";s:8:\"\u0000*\u0000scope\";s:43:\"esi-contracts.read_corporation_contracts.v1\";s:7:\"\u0000*\u0000tags\";a:3:{i:0;s:11:\"corporation\";i:1;s:9:\"contracts\";i:2;s:4:\"bids\";}s:7:\"\u0000*\u0000page\";i:1;s:5:\"tries\";i:1;s:8:\"\u0000*\u0000roles\";a:0:{}s:15:\"\u0000*\u0000request_body\";a:0:{}s:15:\"\u0000*\u0000query_string\";a:0:{}s:8:\"\u0000*\u0000token\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":3:{s:5:\"class\";s:31:\"Seat\\Eveapi\\Models\\RefreshToken\";s:2:\"id\";i:<removed>;s:10:\"connection\";s:5:\"mysql\";}s:9:\"\u0000*\u0000client\";N;s:14:\"\u0000*\u0000public_call\";N;s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}"
  ]
}
```

**Comment by warlof** [comment]
@MrBMT do you still have this issue since last package versions ?

At time :
eveseat/api@3.0.3
eveseat/console@3.0.2
eveseat/eveapi@3.0.4
eveseat/notifications@3.0.1
eveseat/web@3.0.6
eveseat/services@3.0.2

**Comment by MrBMT** [comment]
As far as I can see, this seems to be resolved with the latest package versions, so I'm closing this one off @warlof
