### ISSUE TITLE
SSL Gateway giving me a headache

### ISSUE THREAD

**Issue by flyingferret** [eveseat/seat#317]
With a SSl gateway setup and domain records all updated. the landing page is no "Whoops something went wrong"  in debug more i get 

> The request has both a trusted "FORWARDED" header and a trusted "X_FORWARDED_PORT" header, conflicting with each other. You should either configure your proxy to remove one of them, or configure your project to distrust the offending one

i'm no expert with nginx, sorry in advance, 

The log error that appears.

```
[2018-05-17 20:21:59] local.ERROR: The request has both a trusted "FORWARDED" header and a trusted "X_$
[stacktrace]
#0 /var/www/seat/vendor/symfony/http-foundation/Request.php(1026): Symfony\\Component\\HttpFoundation\$
#1 /var/www/seat/vendor/symfony/http-foundation/Request.php(1094): Symfony\\Component\\HttpFoundation\$
#2 /var/www/seat/vendor/symfony/http-foundation/Request.php(1127): Symfony\\Component\\HttpFoundation\$
#3 /var/www/seat/vendor/symfony/http-foundation/Request.php(1143): Symfony\\Component\\HttpFoundation\$
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Http/Request.php(99): Symfony\\Component\\Htt$
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Http/Request.php(113): Illuminate\\Http\\Requ$
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(158): Ill$
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(69): Illu$
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Sessi$
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipelin$
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse$
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cook$
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeli$
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Il$
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cook$
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeli$
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Rout$
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipelin$
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing$
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing$
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing$
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\$
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Founda$
#23 /var/www/seat/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illu$
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy$
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeli$
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest$
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foun$
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeli$
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest$
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foun$
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeli$
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.$
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foun$
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeli$
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenan$
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foun$
#37 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeli$
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Rout$
#39 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\$
#40 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\$
#41 /var/www/seat/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate$
#42 {main}
"}


[2018-05-17 20:45:02] local.ERROR: Class 'Seat\Eveapi\Models\Eve\ApiKey' not found {"exception":"[obje$
[stacktrace]
#0 /var/www/seat/vendor/eveseat/notifications/src/Alerts/Base.php(73): Seat\\Notifications\\Alerts\\Se$
#1 /var/www/seat/vendor/eveseat/notifications/src/Commands/AlertsRun.php(72): Seat\\Notifications\\Ale$
#2 [internal function]: Seat\\Notifications\\Commands\\AlertsRun->handle()
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func$
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Co$
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Co$
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Con$
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Contain$
#8 /var/www/seat/vendor/symfony/console/Command/Command.php(252): Illuminate\\Console\\Command->execut$
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\$
#10 /var/www/seat/vendor/symfony/console/Application.php(946): Illuminate\\Console\\Command->run(Objec$
#11 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Applicatio$
#12 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Applicatio$
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Compon$
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illumina$
#15 /var/www/seat/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Compone$
#16 {main}
"}
```

site config is:

```
server {

        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        root /var/www/seat/public;
        index index.php index.html index.htm;

        # Make site accessible from http://localhost/
        server_name seat.sseek.space;

        location / {
                try_files $uri $uri/ /index.php?$query_string;
        }
        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
        }
}
```

my ssl gateway > host is no in https mode, 

and prior to enabling the SSL gateway everything was runnning correct.

 * Getting environment information
WARNING: This command is running as root!
WARNING: Running as root means that we will probably be able to access any file on your system. This command will not be able to help diagnose permission problems this way.
Current User: root
PHP Version: 7.1.17-1+ubuntu16.04.1+deb.sury.org+1
Host OS: Linux vps521732 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64
SeAT Basepath: /var/www/seat
```

 * Checking DEBUG mode
Debug mode is enabled. This is not recommended in production!

 * Checking storage
/var/www/seat/storage is writable
/var/www/seat/storage/logs is writable
/var/www/seat/storage/eseye is writable
/var/www/seat/storage/sde/ is writable
/var/www/seat/storage/logs/laravel.log is not writable

 * Checking Database
+------------+------------------------------------------+
| Setting    | Value                                    |
+------------+------------------------------------------+
| Connection | mysql                                    |
| Host       | 127.0.0.1                                |
| Database   | seat                                     |
| Username   | seat                                     |
| Password   | **************************************** |
+------------+------------------------------------------+
Connection OK to database: seat

 * Checking Redis
+----------+-----------+
| Setting  | Value     |
+----------+-----------+
| Host     | 127.0.0.1 |
| Port     | 6379      |
| Database | 0         |
+----------+-----------+
Connected to Redis
Set random key of: LLKjdujx9Xxqecq1jetw7NmGa5mBHM3RIkQXhILkUqQGnnUUm5HrXgNl9YXa7t2J
Set key to expire in 10 sec
Read key OK

 * Checking ESI Access
Server Online Since: 2018-05-17T11:05:20Z
Online Players: 28189
ESI appears to be OK

Checking Local and Github Versions. Please wait...
+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 3.0.0-beta5   | 2.0.10        |
| Console       | 3.0.0-beta4   | 2.0.4         |
| Eveapi        | 3.0.0-beta11  | 2.0.14        |
| Notifications | 3.0.0-beta2   | 2.0.11        |
| Web           | 3.0.0-beta9   | 2.0.19        |
| Services      | 3.0.0-beta6   | 2.0.13        |
+---------------+---------------+---------------+
SeAT Diagnostics complete
```

* **Problem**: _Whats wrong?_
* **Expected**: _What did you expect to happen?_
* **Logs / Screenshots / Proof**: _The more information you give the better!_
* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

**Comment by MrBMT** [comment]
Is there a particular reason why you're not just letting Nginx handle the HTTPS?
Install certbot-nginx for Ubuntu: https://certbot.eff.org/lets-encrypt/ubuntuxenial-nginx - get your free SSL, then use the config bellow:

```
server {
    listen [::]:80;
    listen 80;
    server_name seat.sseek.space;

    location / {
        return 301 https://seat.sseek.space$request_uri;
    }
}

server {
    listen [::]:443 ssl http2;
    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/seat.sseek.space/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/seat.sseek.space/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    root /var/www/seat/public;
    index index.php index.html index.htm;

    server_name seat.sseek.space;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # pass PHP scripts to FastCGI server
    #
    location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
    }
}
```

**Comment by leonjza** [comment]
I believe this was solved in the support channel.
