### ISSUE TITLE
CustomsOfficeLocations Job error

### ISSUE THREAD

**Issue by MrBMT** [eveseat/seat#346]
* **Problem**: _The customs office job tries to check for pocos even if a user does not have a role that allows them to view those details, resulting in a ton of these errors_
* **Expected**: _It not to check for that user, unless they have the required role_
* **Logs / Screenshots / Proof**: _See below_
* **Version Info**: _PHP 7.1, Debian 9 host install_
```
+---------------+---------------+
| Package Name  | Local Version |
+---------------+---------------+
| Api           | 3.0.0-beta5   | 
| Console       | 3.0.0-beta8   |
| Eveapi        | 3.0.0-beta17  |
| Notifications | 3.0.0-beta3   |
| Web           | 3.0.0-beta17  |
| Services      | 3.0.0-beta11  |
+---------------+---------------+
```

```
Seat\Eveapi\Jobs\PlanetaryInteraction\Corporation\CustomsOfficeLocations
ID 749725
Queue default
Tags corporation, customs_offices, locations, character_id:<removed>
Failed At 18-05-27 15:08:01

Error

Seat\Eseye\Exceptions\RequestFailedException: Character does not have required role(s) in /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php:242Stack trace:
#0 /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php(102): Seat\Eseye\Fetchers\GuzzleFetcher->httpRequest('post', 'https://esi.eve...', Array, '[1024893937568,...')
#1 /var/www/seat/vendor/eveseat/eseye/src/Eseye.php(448): Seat\Eseye\Fetchers\GuzzleFetcher->call('post', 'https://esi.eve...', Array)
#2 /var/www/seat/vendor/eveseat/eseye/src/Eseye.php(256): Seat\Eseye\Eseye->rawFetch('post', 'https://esi.eve...', Array)
#3 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/EsiBase.php(327): Seat\Eseye\Eseye->invoke('post', Object(GuzzleHttp\Psr7\Uri), Array)
#4 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/PlanetaryInteraction/Corporation/CustomsOfficeLocations.php(82): Seat\Eveapi\Jobs\EsiBase->retrieve(Array)
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Seat\Eveapi\Jobs\PlanetaryInteraction\Corporation\CustomsOfficeLocations->Seat\Eveapi\Jobs\PlanetaryInteraction\Corporation\{closure}(Object(Illuminate\Support\Collection), 0)
#6 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/PlanetaryInteraction/Corporation/CustomsOfficeLocations.php(108): Illuminate\Support\Collection->each(Object(Closure))
#7 [internal function]: Seat\Eveapi\Jobs\PlanetaryInteraction\Corporation\CustomsOfficeLocations->handle()
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\PlanetaryInteraction\Corporation\CustomsOfficeLocations))
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\PlanetaryInteraction\Corporation\CustomsOfficeLocations))
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\PlanetaryInteraction\Corporation\CustomsOfficeLocations), false)
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high,medium,low...')
#23 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#29 /var/www/seat/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#31 /var/www/seat/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/seat/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 {main}

Data

{
  "method": "post",
  "endpoint": "/corporations/{corporation_id}/assets/locations/",
  "version": "v2",
  "scope": "esi-assets.read_assets.v1",
  "tags": [
    "corporation",
    "customs_offices",
    "locations"
  ],
  "tries": 1,
  "roles": [],
  "page": null,
  "request_body": [],
  "query_string": [],
  "token": {
    "class": "Seat\\Eveapi\\Models\\RefreshToken",
    "id": <removed>,
    "connection": "mysql"
  },
  "client": null,
  "public_call": null,
  "job": null,
  "connection": null,
  "queue": null,
  "chainConnection": null,
  "chainQueue": null,
  "delay": null,
  "chained": []
}
```

**Comment by leonjza** [comment]
Thanks for the report. Adding the appropriate `$roles` attribute to the [job](https://github.com/eveseat/eveapi/blob/master/src/Jobs/PlanetaryInteraction/Corporation/CustomsOfficeLocations.php) should fix this. Example for wallet transactions [here](https://github.com/eveseat/eveapi/blob/master/src/Jobs/Wallet/Corporation/Transactions.php#L58).

I don't have tokens with POCOS so I am not sure what the correct roles are, if someone wants to help do a lookup/ping someone that knows.

**Comment by MrBMT** [comment]
Thanks, did some testing with my CEO earlier and worked out it requires the accountant role of all things. I've submitted a PR to fix this.
