### ISSUE TITLE
MemberSecurity API Issue

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#40]
Last Updater: Processing: MemberSecurity

Exception: ErrorException
Error Code: 0
Error Message: Undefined index: titles
File: /var/www/seat/vendor/3rdpartyeve/phealng/lib/Pheal/Core/RowSetRow.php - Line: 66

```
Traceback: #0 /var/www/seat/vendor/3rdpartyeve/phealng/lib/Pheal/Core/RowSetRow.php(66): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/seat/v...', 66, Array)
#1 /var/www/seat/vendor/eveseat/eveapi/src/Api/Corporation/MemberSecurity.php(79): Pheal\Core\RowSetRow->__get('titles')
#2 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/UpdateAuthenticated.php(99): Seat\Eveapi\Api\Corporation\MemberSecurity->call()
#3 [internal function]: Seat\Eveapi\Jobs\UpdateAuthenticated->handle()
#4 /var/www/seat/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array)
#5 /var/www/seat/bootstrap/cache/compiled.php(9441): Illuminate\Container\Container->call(Array)
#6 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#7 /var/www/seat/bootstrap/cache/compiled.php(9593): call_user_func(Object(Closure), Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#8 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#9 /var/www/seat/bootstrap/cache/compiled.php(9575): call_user_func(Object(Closure), Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#10 /var/www/seat/bootstrap/cache/compiled.php(9448): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(43): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\UpdateAuthenticated), Object(Closure))
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/RedisJob.php(50): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(208): Illuminate\Queue\Jobs\RedisJob->fire()
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), '1', '0')
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(109): Illuminate\Queue\Worker->pop(NULL, 'default', '0', '3', '1')
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(71): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, 'default', '0', '128', false)
#18 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#19 /var/www/seat/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array)
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#21 /var/www/seat/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/seat/vendor/symfony/console/Application.php(837): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/seat/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/seat/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/seat/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 {main}
```

I have no idea what this error means.  Any help so I can fix it?  Also the key has all areas of the api key enabled.

**Comment by leonjza** [comment]
It means the XML that the EVE XML Api returned did not have the titles rowset defined like [here](https://github.com/eveseat/eveapi/blob/master/xml_samples/corporation/MemberSecurity.xml#L23)

**Comment by drkthunder02** [comment]
What other information do you need from me in order to help you all with this issue?

**Comment by leonjza** [comment]
Ill probably need the Api to try replicate the issue. Although, I have no idea why CCP wont return that rowset.

**Comment by drkthunder02** [comment]
Send me your email or eve name, and I will get you the key id and verification code.

**Comment by leonjza** [comment]
Just pm me on on slack/irc.

**Comment by leonjza** [comment]
Sigh. CCP :rage: The API is missing the `titles` rowset for one of the members in your corporation. First time I am seeing this. Just waiting to hear of this is actually optional then Ill push a fix for it.

**Comment by leonjza** [comment]
Ok, looks like there is an API bug with Dust Characters where a table join on CCP's side may not be including their `titles`. Will see how long it takes to fix and maybe implement a temp workaround for now.

**Comment by leonjza** [comment]
```
CCP Tellus [3:15 PM] 
@qu1ckkkk: yes, that's getting fixed with the next Tuesday release.
```

**Comment by leonjza** [comment]
_Corporation titles carried by DUST characters now show up in the corp/MemberSecurity endpoint._
https://community.eveonline.com/news/patch-notes/patch-notes-for-january-2016-release
