### ISSUE TITLE
Error screen when try see selected evemail

### ISSUE THREAD

**Issue by MagnusIIIBR** [eveseat/seat#430]
* **Problem**: Open a error screen when i try see a selected evemail
* **Expected**: See the selected evemail.
* **Logs / Screenshots / Proof**: 

[2018-08-21 00:28:03] local.ERROR: Trying to get property of non-object (View: /var/www/seat/vendor/eveseat/web/src/resources/views/character/partials/messagethread.blade.php) (View: /var/www/seat/vendor/eveseat/web/src/resources/views/character/partials/messagethread.blade.php) {"userId":2113805965,"email":"myemail@gmail.com","exception":"[object] (ErrorException(code: 0): Trying to get property of non-object (View: /var/www/seat/vendor/eveseat/web/src/resources/views/character/partials/messagethread.blade.php) (View: /var/www/seat/vendor/eveseat/web/src/resources/views/character/partials/messagethread.blade.php) at /var/www/seat/storage/framework/views/95fb3b49c8e6cfee6971a37df0a1735a614f96a8.php:3, ErrorException(code: 0): Trying to get property of non-object (View: /var/www/seat/vendor/eveseat/web/src/resources/views/character/partials/messagethread.blade.php) at /var/www/seat/storage/framework/views/95fb3b49c8e6cfee6971a37df0a1735a614f96a8.php:3, ErrorException(code: 0): Trying to get property of non-object at /var/www/seat/storage/framework/views/95fb3b49c8e6cfee6971a37df0a1735a614f96a8.php:3)
[stacktrace]
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/var/www/seat/s...', Array)
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/View.php(137): Illuminate\\View\\Engines\\CompilerEngine->get('/var/www/seat/v...', Array)
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\\View\\View->getContents()
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\\View\\View->renderContents()
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#6 /var/www/seat/vendor/symfony/http-foundation/Response.php(206): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View))
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
![image](https://user-images.githubusercontent.com/9530663/44373834-a9403180-a4c1-11e8-86d3-40a55df5a306.png)
![image](https://user-images.githubusercontent.com/9530663/44373837-aba28b80-a4c1-11e8-9c86-8378aa10614f.png)

**Comment by MagnusIIIBR** [comment]
I restarted the server and worked.
