### ISSUE TITLE
Hundreds of these errors

### ISSUE THREAD

**Issue by entropylaw** [eveseat/seat#447]
```
Error
Seat\Eseye\Exceptions\RequestFailedException in /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php:242
Stack trace:
#0 /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php(168): Seat\Eseye\Fetchers\GuzzleFetcher->httpRequest('post', 'https://login.e...', Array)
#1 /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php(148): Seat\Eseye\Fetchers\GuzzleFetcher->refreshToken()
#2 /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php(99): Seat\Eseye\Fetchers\GuzzleFetcher->getToken()
#3 /var/www/seat/vendor/eveseat/eseye/src/Eseye.php(448): Seat\Eseye\Fetchers\GuzzleFetcher->call('get', 'https://esi.eve...', Array)
#4 /var/www/seat/vendor/eveseat/eseye/src/Eseye.php(256): Seat\Eseye\Eseye->rawFetch('get', 'https://esi.eve...', Array)
#5 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/EsiBase.php(218): Seat\Eseye\Eseye->invoke('get', Object(GuzzleHttp\Psr7\Uri), Array)
#6 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/PlanetaryInteraction/Corporation/CustomsOffices.php(101): Seat\Eveapi\Jobs\EsiBase->retrieve(Array)
#7 [internal function]: Seat\Eveapi\Jobs\PlanetaryInteraction\Corporation\CustomsOffices->handle()
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\PlanetaryInteraction\Corporation\CustomsOffices))
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\PlanetaryInteraction\Corporation\CustomsOffices))
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\PlanetaryInteraction\Corporation\CustomsOffices), false)
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high,medium,low...')
#23 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#29 /var/www/seat/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#31 /var/www/seat/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/seat/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 {main}


Data
{
  "method": "get",
  "endpoint": "/corporations/{corporation_id}/customs_offices/",
  "version": "v1",
  "scope": "esi-planets.read_customs_offices.v1",
  "roles": [
    "Director"
  ],
  "tags": [
    "corporation",
    "customs_offices"
  ],
  "page": 1,
  "known_structures": {
    "items": []
  },
  "tries": 1,
  "request_body": [],
  "query_string": [],
  "token": {
    "class": "Seat\\Eveapi\\Models\\RefreshToken",
    "id": 2113177776,
    "connection": "mysql"
  },
  "client": null,
  "public_call": null,
  "job": null,
  "connection": null,
  "queue": "default",
  "chainConnection": null,
  "chainQueue": null,
  "delay": null,
  "chained": [
    "O:72:\"Seat\\Eveapi\\Jobs\\PlanetaryInteraction\\Corporation\\CustomsOfficeLocations\":23:{s:9:\"\u0000*\u0000method\";s:4:\"post\";s:11:\"\u0000*\u0000endpoint\";s:48:\"/corporations/{corporation_id}/assets/locations/\";s:10:\"\u0000*\u0000version\";s:2:\"v2\";s:8:\"\u0000*\u0000scope\";s:25:\"esi-assets.read_assets.v1\";s:8:\"\u0000*\u0000roles\";a:1:{i:0;s:8:\"Director\";}s:7:\"\u0000*\u0000tags\";a:3:{i:0;s:11:\"corporation\";i:1;s:15:\"customs_offices\";i:2;s:9:\"locations\";}s:5:\"tries\";i:1;s:7:\"\u0000*\u0000page\";N;s:15:\"\u0000*\u0000request_body\";a:0:{}s:15:\"\u0000*\u0000query_string\";a:0:{}s:8:\"\u0000*\u0000token\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":3:{s:5:\"class\";s:31:\"Seat\\Eveapi\\Models\\RefreshToken\";s:2:\"id\";i:2113177776;s:10:\"connection\";s:5:\"mysql\";}s:9:\"\u0000*\u0000client\";N;s:14:\"\u0000*\u0000public_call\";N;s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}s:16:\"\u0000*\u0000ratelimit_key\";s:12:\"esiratelimit\";s:12:\"\u0000*\u0000ratelimit\";i:80;s:21:\"\u0000*\u0000ratelimit_duration\";i:5;}"
  ],
  "ratelimit_key": "esiratelimit",
  "ratelimit": 80,
  "ratelimit_duration": 5
}
```

**Comment by leonjza** [comment]
Something is probably up with your setup and the SSO configuration. I'd double check that and if you don't win, join slack for some support.

For Slack invites, please see: https://eveseat.github.io/docs/about/contact/
