### ISSUE TITLE
General error: 1364 Field 'characterId' doesn't have a default value

### ISSUE THREAD

**Issue by fwfmiao** [eveseat/seat#450]
i use https://seat.xxxx.com/api/v2/users add use,bur report bug
{
    "message": "Server Error"
}

laravel-2018-10-03.log

[2018-10-03 05:44:46] local.ERROR: SQLSTATE[HY000]: General error: 1364 Field 'characterId' doesn't have a default value (SQL: insert into `refresh_tokens` (`refresh_token`, `scopes`, `token`, `expires_on`, `character_id`, `updated_at`, `created_at`) values (EE8-_GM4sRW-_lZYHH32Udzl315rVMjj711-E-EmRXMd0db_XKlxGVykLGKAoVWUSTIudGkotjlbHfKYAn4Afcrx5yM-elu7Wa-lgnJyY10LRCKr-kGWF62bpMi2QGqajL35b2dnF2kswix2X7uRlEC5YgSlvaPKLF715F-3sXx0j9AoHRIyegm3XU_zN15PsXJVuF60VSvITs3GYZQZoC1qeZhckXtQ4NERXujtKjPE5bIa9NpZpawWKqhLmU5o6wf0WDxE6SWLmkjAlqNEfPaCVWLb-tNsf6QbWlFIydtZVEIM4v_oJ5xZ7tTQPqC0kGZaFeR8A6q3b9RbrPW700HyApL640RLNtibKHeN-wYlt04Mzw2oCvCJTlu4UYAMFgAM4Hpr1kW34srYwmBOfA2, ["esi-calendar.read_calendar_events.v1","esi-location.read_location.v1","esi-location.read_ship_type.v1","esi-mail.read_mail.v1","esi-skills.read_skills.v1","esi-skills.read_skillqueue.v1","esi-wallet.read_character_wallet.v1","esi-search.search_structures.v1","esi-clones.read_clones.v1","esi-characters.read_contacts.v1","esi-universe.read_structures.v1","esi-bookmarks.read_character_bookmarks.v1","esi-killmails.read_killmails.v1","esi-corporations.read_corporation_membership.v1","esi-assets.read_assets.v1","esi-planets.manage_planets.v1","esi-fleets.read_fleet.v1","esi-ui.open_window.v1","esi-fittings.read_fittings.v1","esi-markets.structure_markets.v1","esi-corporations.read_structures.v1","esi-characters.read_loyalty.v1","esi-characters.read_opportunities.v1","esi-characters.read_chat_channels.v1","esi-characters.read_medals.v1","esi-characters.read_standings.v1","esi-characters.read_agents_research.v1","esi-industry.read_character_jobs.v1","esi-markets.read_character_orders.v1","esi-characters.read_blueprints.v1","esi-characters.read_corporation_roles.v1","esi-location.read_online.v1","esi-contracts.read_character_contracts.v1","esi-clones.read_implants.v1","esi-characters.read_fatigue.v1","esi-killmails.read_corporation_killmails.v1","esi-corporations.track_members.v1","esi-wallet.read_corporation_wallets.v1","esi-characters.read_notifications.v1","esi-corporations.read_divisions.v1","esi-corporations.read_contacts.v1","esi-assets.read_corporation_assets.v1","esi-corporations.read_titles.v1","esi-corporations.read_blueprints.v1","esi-bookmarks.read_corporation_bookmarks.v1","esi-contracts.read_corporation_contracts.v1","esi-corporations.read_standings.v1","esi-corporations.read_starbases.v1","esi-industry.read_corporation_jobs.v1","esi-markets.read_corporation_orders.v1","esi-corporations.read_container_logs.v1","esi-industry.read_character_mining.v1","esi-industry.read_corporation_mining.v1","esi-planets.read_customs_offices.v1","esi-corporations.read_facilities.v1","esi-corporations.read_medals.v1","esi-characters.read_titles.v1","esi-alliances.read_contacts.v1","esi-characters.read_fw_stats.v1","esi-corporations.read_fw_stats.v1","esi-characterstats.read.v1"], -, 2018-10-03 05:44:46, 2114269657, 2018-10-03 05:44:46, 2018-10-03 05:44:46)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'characterId' doesn't have a default value (SQL: insert into `refresh_tokens` (`refresh_token`, `scopes`, `token`, `expires_on`, `character_id`, `updated_at`, `created_at`) values (EE8-_GM4sRW-_lZYHH32Udzl315rVMjj711-E-EmRXMd0db_XKlxGVykLGKAoVWUSTIudGkotjlbHfKYAn4Afcrx5yM-elu7Wa-lgnJyY10LRCKr-kGWF62bpMi2QGqajL35b2dnF2kswix2X7uRlEC5YgSlvaPKLF715F-3sXx0j9AoHRIyegm3XU_zN15PsXJVuF60VSvITs3GYZQZoC1qeZhckXtQ4NERXujtKjPE5bIa9NpZpawWKqhLmU5o6wf0WDxE6SWLmkjAlqNEfPaCVWLb-tNsf6QbWlFIydtZVEIM4v_oJ5xZ7tTQPqC0kGZaFeR8A6q3b9RbrPW700HyApL640RLNtibKHeN-wYlt04Mzw2oCvCJTlu4UYAMFgAM4Hpr1kW34srYwmBOfA2, [\"esi-calendar.read_calendar_events.v1\",\"esi-location.read_location.v1\",\"esi-location.read_ship_type.v1\",\"esi-mail.read_mail.v1\",\"esi-skills.read_skills.v1\",\"esi-skills.read_skillqueue.v1\",\"esi-wallet.read_character_wallet.v1\",\"esi-search.search_structures.v1\",\"esi-clones.read_clones.v1\",\"esi-characters.read_contacts.v1\",\"esi-universe.read_structures.v1\",\"esi-bookmarks.read_character_bookmarks.v1\",\"esi-killmails.read_killmails.v1\",\"esi-corporations.read_corporation_membership.v1\",\"esi-assets.read_assets.v1\",\"esi-planets.manage_planets.v1\",\"esi-fleets.read_fleet.v1\",\"esi-ui.open_window.v1\",\"esi-fittings.read_fittings.v1\",\"esi-markets.structure_markets.v1\",\"esi-corporations.read_structures.v1\",\"esi-characters.read_loyalty.v1\",\"esi-characters.read_opportunities.v1\",\"esi-characters.read_chat_channels.v1\",\"esi-characters.read_medals.v1\",\"esi-characters.read_standings.v1\",\"esi-characters.read_agents_research.v1\",\"esi-industry.read_character_jobs.v1\",\"esi-markets.read_character_orders.v1\",\"esi-characters.read_blueprints.v1\",\"esi-characters.read_corporation_roles.v1\",\"esi-location.read_online.v1\",\"esi-contracts.read_character_contracts.v1\",\"esi-clones.read_implants.v1\",\"esi-characters.read_fatigue.v1\",\"esi-killmails.read_corporation_killmails.v1\",\"esi-corporations.track_members.v1\",\"esi-wallet.read_corporation_wallets.v1\",\"esi-characters.read_notifications.v1\",\"esi-corporations.read_divisions.v1\",\"esi-corporations.read_contacts.v1\",\"esi-assets.read_corporation_assets.v1\",\"esi-corporations.read_titles.v1\",\"esi-corporations.read_blueprints.v1\",\"esi-bookmarks.read_corporation_bookmarks.v1\",\"esi-contracts.read_corporation_contracts.v1\",\"esi-corporations.read_standings.v1\",\"esi-corporations.read_starbases.v1\",\"esi-industry.read_corporation_jobs.v1\",\"esi-markets.read_corporation_orders.v1\",\"esi-corporations.read_container_logs.v1\",\"esi-industry.read_character_mining.v1\",\"esi-industry.read_corporation_mining.v1\",\"esi-planets.read_customs_offices.v1\",\"esi-corporations.read_facilities.v1\",\"esi-corporations.read_medals.v1\",\"esi-characters.read_titles.v1\",\"esi-alliances.read_contacts.v1\",\"esi-characters.read_fw_stats.v1\",\"esi-corporations.read_fw_stats.v1\",\"esi-characterstats.read.v1\"], -, 2018-10-03 05:44:46, 2114269657, 2018-10-03 05:44:46, 2018-10-03 05:44:46)) at /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'characterId' doesn't have a default value at /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:144, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'characterId' doesn't have a default value at /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:142)
[stacktrace]
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into `re...', Array, Object(Closure))
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into `re...', Array, Object(Closure))
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into `re...', Array)
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert('insert into `re...', Array)
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2159): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId(Object(Illuminate\\Database\\Query\\Builder), 'insert into `re...', Array, 'character_id')
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1283): Illuminate\\Database\\Query\\Builder->insertGetId(Array, 'character_id')
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(722): Illuminate\\Database\\Eloquent\\Builder->__call('insertGetId', Array)
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(687): Illuminate\\Database\\Eloquent\\Model->insertAndSetId(Object(Illuminate\\Database\\Eloquent\\Builder), Array)
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(550): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Illuminate\\Database\\Eloquent\\Builder))
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(250): Illuminate\\Database\\Eloquent\\Model->save()
#10 /var/www/seat/vendor/eveseat/api/src/Http/Controllers/Api/v2/UserController.php(345): Illuminate\\Database\\Eloquent\\Relations\\HasOneOrMany->save(Object(Seat\\Eveapi\\Models\\RefreshToken))
#11 [internal function]: Seat\\Api\\Http\\Controllers\\Api\\v2\\UserController->postNewUser(Object(Seat\\Api\\Http\\Validation\\NewUser))
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('postNewUser', Array)
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Seat\\Api\\Http\\Controllers\\Api\\v2\\UserController), 'postNewUser')
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/seat/vendor/eveseat/api/src/Http/Middleware/ApiToken.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Seat\\Api\\Http\\Middleware\\ApiToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/seat/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#45 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#46 /var/www/seat/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#47 {main}
"}

**Comment by warlof** [comment]
Hi,

Can you give us the request you made as well?

**Comment by fwfmiao** [comment]
![image](https://user-images.githubusercontent.com/29328241/46399421-36fe7600-c72a-11e8-82e1-885fcc141dda.png)
