### ISSUE TITLE
ESI Scopes is not working 

### ISSUE THREAD

**Issue by Discoklaus** [eveseat/seat#562]
after config the .env file like in the documentation and login on my website i get back 

ERR_CONNECTION_REFUSED

in think the server is not responds on my request, in my firewall log i can see my server is 
communicating with the eve esi website but after this nothing happend.
my externel adress and the adress i put in to the esi website and in my .env file is:
https://external-IP:8442/auth/eve/callback
running at a ubuntu

atm i stuck at the point "Configuring Eve Online ESI-Scopes"

**Comment by warlof** [comment]
Hi,

You may have a diff between scopes selected on your EVE App and those requested into your SeAT.
Double check them - on SeAT side, they're filled into `Settings` > `Single Sign-On`.

They must **exactly** be the same.

**Comment by LordMrcS** [comment]
In my case I just added them all, both in Seat as in the EVE API management and I get this:

 (1/1) ClientException
Client error: `POST https://login.eveonline.com/oauth/token` resulted in a `400 Bad Request` response:
{"error":"invalid_request","error_description":"The code parameter is missing"}

at Client->request('post', 'https://login.eveonline.com/oauth/token', array('headers' => array('Accept' => 'application/json'), 'form_params' => array('client_id' => 'my ID is also OK', 'client_secret' => 'my secret is OK', 'code' => **null**, 'redirect_uri' => 'http://seat.spray.ml/auth/eve/callback', 'grant_type' => 'authorization_code'), 'synchronous' => true))in Client.php line 89

I believe there's a bug sending that null in the var code above. Tried reinstalling freshly 3 times already and even via docker. Same results.

**Comment by warlof** [comment]
Hi, 

Can you give me the exact :
 - address you have into your browser while landing in the login page
 - address you have into your browser while beeing on the ccp login page
 - address you have into your browser when you get the error
- value of both `APP_URL` and `EVE_CALLBACK_URL` from the `.env` file

In addition : 
- what's the version of php you are using
- are you using SSL

Compare to the amount of running instance, I honestly think it's a setup mistake 😜

**Comment by LordMrcS** [comment]
I'm installing in http://seat.spray.ml

Login at http://seat.spray.ml/auth/login

Request authorization at:
`https://login.eveonline.com/oauth/authorize?client_id=0db65e00604a46ae891a5b062ccc312d&redirect_uri=http%3A%2F%2Fseat.spray.ml%2Fauth%2Feve%2Fcallback&scope=esi-alliances.read_contacts.v1+esi-assets.read_assets.v1+esi-assets.read_corporation_assets.v1+esi-bookmarks.read_character_bookmarks.v1+esi-bookmarks.read_corporation_bookmarks.v1+esi-calendar.read_calendar_events.v1+esi-characters.read_agents_research.v1+esi-characters.read_blueprints.v1+esi-characters.read_chat_channels.v1+esi-characters.read_contacts.v1+esi-characters.read_corporation_roles.v1+esi-characters.read_fatigue.v1+esi-characters.read_fw_stats.v1+esi-characters.read_loyalty.v1+esi-characters.read_medals.v1+esi-characters.read_notifications.v1+esi-characters.read_opportunities.v1+esi-characters.read_standings.v1+esi-characters.read_titles.v1+esi-characterstats.read.v1+esi-clones.read_clones.v1+esi-clones.read_implants.v1+esi-contracts.read_character_contracts.v1+esi-contracts.read_corporation_contracts.v1+esi-corporations.read_blueprints.v1+esi-corporations.read_contacts.v1+esi-corporations.read_container_logs.v1+esi-corporations.read_corporation_membership.v1+esi-corporations.read_divisions.v1+esi-corporations.read_facilities.v1+esi-corporations.read_fw_stats.v1+esi-corporations.read_medals.v1+esi-corporations.read_standings.v1+esi-corporations.read_starbases.v1+esi-corporations.read_structures.v1+esi-corporations.read_titles.v1+esi-corporations.track_members.v1+esi-fittings.read_fittings.v1+esi-fleets.read_fleet.v1+esi-industry.read_character_jobs.v1+esi-industry.read_character_mining.v1+esi-industry.read_corporation_jobs.v1+esi-industry.read_corporation_mining.v1+esi-killmails.read_corporation_killmails.v1+esi-killmails.read_killmails.v1+esi-location.read_location.v1+esi-location.read_online.v1+esi-location.read_ship_type.v1+esi-mail.read_mail.v1+esi-markets.read_character_orders.v1+esi-markets.read_corporation_orders.v1+esi-markets.structure_markets.v1+esi-planets.manage_planets.v1+esi-planets.read_customs_offices.v1+esi-search.search_structures.v1+esi-skills.read_skillqueue.v1+esi-skills.read_skills.v1+esi-ui.open_window.v1+esi-universe.read_structures.v1+esi-wallet.read_character_wallet.v1+esi-wallet.read_corporation_wallets.v1&response_type=code&state=dznL7HGwiEjOZut7XnZSTBgn7ZWIBTL7Y143Dkf0`

Authorization at:
`http://seat.spray.ml/auth/eve/callback?code=zN5b7D_wG5vxiLokVEMngIHBFas8im4yGewGh_rSgF0372sgZIi_Ld3wrzEPmHQw&state=dznL7HGwiEjOZut7XnZSTBgn7ZWIBTL7Y143Dkf0`

This is where I get Whoops, looks like something went wrong. 

The code I sent earlier was from debug at this last link.

**Comment by LordMrcS** [comment]
Forgot to add: 

No SSL. 

PHP 7.2.19-0ubuntu0.18.04.1 + Nginx + MySQL

**Comment by warlof** [comment]
Can you provide the full stack of the error ?
You only provide the head which contains really few information ^^

Is your nginx behind a proxy or something ?
Did you double check sessions configuration at PHP level ?

**Comment by LordMrcS** [comment]
```
(1/1)                                     ClientException                                                                  Client error: `POST https://login.eveonline.com/oauth/token` resulted in a `400 Bad Request` response: {"error":"invalid_request","error_description":"The code parameter is missing"}
--
in RequestException.php line 113
at RequestException::create(object(Request), object(Response))in Middleware.php line 66
at Middleware::GuzzleHttp\{closure}(object(Response))in Promise.php line 203
at Promise::callHandler(1, object(Response), array(object(Promise), object(Closure), null))in Promise.php line 156
at Promise::GuzzleHttp\Promise\{closure}()in TaskQueue.php line 47
at TaskQueue->run(true)in Promise.php line 246
at Promise->invokeWaitFn()in Promise.php line 223
at Promise->waitIfPending()in Promise.php line 267
at Promise->invokeWaitList()in Promise.php line 225
at Promise->waitIfPending()in Promise.php line 62
at Promise->wait()in Client.php line 131
at Client->request('post', 'https://login.eveonline.com/oauth/token', array('headers' => array('Accept' => 'application/json'), 'form_params' => array('client_id'  => '0db65e00604a46ae891a5b062ccc312d', 'client_secret' =>  'secret removed by me', 'code' => null, 'redirect_uri' => 'http://seat.spray.ml/auth/eve/callback', 'grant_type' => 'authorization_code'), 'synchronous' => true))in Client.php line 89
at Client->__call('post', array('https://login.eveonline.com/oauth/token', array('headers' => array('Accept' => 'application/json'), 'form_params' => array('client_id'  => '0db65e00604a46ae891a5b062ccc312d', 'client_secret' =>  'secret removed by me', 'code' => null, 'redirect_uri' => 'http://seat.spray.ml/auth/eve/callback', 'grant_type' => 'authorization_code'))))in AbstractProvider.php line 265
at AbstractProvider->getAccessTokenResponse(null)in EveOnlineProvider.php line 62
at EveOnlineProvider->user()in SsoController.php line 65
at SsoController->handleProviderCallback(object(SocialiteManager))
at call_user_func_array(array(object(SsoController), 'handleProviderCallback'), array(object(SocialiteManager)))in Controller.php line 54
at Controller->callAction('handleProviderCallback', array(object(SocialiteManager)))in ControllerDispatcher.php line 45
at ControllerDispatcher->dispatch(object(Route), object(SsoController), 'handleProviderCallback')in Route.php line 212
at Route->runController()in Route.php line 169
at Route->run()in Router.php line 658
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Requirements.php line 78
at Requirements->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 68
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 63
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 66
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 660
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 635
at Router->runRoute(object(Request), object(Route))in Router.php line 601
at Router->dispatchToRoute(object(Request))in Router.php line 590
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 54


```

**Comment by LordMrcS** [comment]
```
[2019-06-27 19:51:25] local.ERROR: Client error: `POST https://login.eveonline.com/oauth/token` resulted in a `400 Bad Request` response:
{"error":"invalid_request","error_description":"The code parameter is missing"}
 {"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 400): Client error: `POST https://login.eveonline.com/oauth/token` resulted in a `400 B$
{\"error\":\"invalid_request\",\"error_description\":\"The code parameter is missing\"}
 at /home/admin/web/seat.spray.ml/public_html/seat/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
[stacktrace]
#0 /home/admin/web/seat.spray.ml/public_html/seat/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\\Exception\\RequestException::create(Object(Guz$
#1 /home/admin/web/seat.spray.ml/public_html/seat/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(Guzzl$
#2 /home/admin/web/seat.spray.ml/public_html/seat/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, Object(Guzzle$
#3 /home/admin/web/seat.spray.ml/public_html/seat/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closu$
#4 /home/admin/web/seat.spray.ml/public_html/seat/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\\Promise\\TaskQueue->run(true)
#5 /home/admin/web/seat.spray.ml/public_html/seat/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#6 /home/admin/web/seat.spray.ml/public_html/seat/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\\Promise\\Promise->waitIfPending()
#7 /home/admin/web/seat.spray.ml/public_html/seat/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#8 /home/admin/web/seat.spray.ml/public_html/seat/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#9 /home/admin/web/seat.spray.ml/public_html/seat/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\\Promise\\Promise->wait()
#10 /home/admin/web/seat.spray.ml/public_html/seat/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\\Client->request('post', 'https://login.e...', Arr$
#11 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/socialite/src/Two/AbstractProvider.php(265): GuzzleHttp\\Client->__call('post', Array)
#12 /home/admin/web/seat.spray.ml/public_html/seat/vendor/eveseat/web/src/Extentions/EveOnlineProvider.php(62): Laravel\\Socialite\\Two\\AbstractProvider->ge$
#13 /home/admin/web/seat.spray.ml/public_html/seat/vendor/eveseat/web/src/Http/Controllers/Auth/SsoController.php(65): Seat\\Web\\Extentions\\EveOnlineProvid$
#14 [internal function]: Seat\\Web\\Http\\Controllers\\Auth\\SsoController->handleProviderCallback(Object(Laravel\\Socialite\\SocialiteManager))
#15 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#16 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Control$
#17 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher-$
#18 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#19 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#20 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\$
#21 /home/admin/web/seat.spray.ml/public_html/seat/vendor/eveseat/web/src/Http/Middleware/Requirements.php(78): Illuminate\\Routing\\Pipeline->Illuminate\\Ro$
#22 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Seat\\Web\\Http\\Middleware\\Requireme$
#23 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illumina$
#24 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing$
#25 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\Subst$
#26 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illumina$
#27 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Ro$
#28 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middlewa$
#29 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illumina$
#30 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routin$
#31 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErr$
#32 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illumina$
#33 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipe$
#34 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\Start$
#35 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illumina$
#36 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\$
#37 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQue$
#38 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illumina$
#39 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pip$
#40 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\Encryp$
#41 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illumina$
#42 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illumin$
#43 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Obje$
#44 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWith$
#45 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Obj$
#46 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRo$
#47 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->disp$
#48 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Il$
#49 /home/admin/web/seat.spray.ml/public_html/seat/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{clos$
#50 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle$
#51 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illumina$
#52 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\$
#53 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middlewa$
#54 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illumina$
#55 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\$
#56 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middlewa$
#57 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illumina$
#58 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\R$
#59 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middlewa$
#60 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illumina$
#61 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illumi$
#62 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middlewa$
#63 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illumina$
#64 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illumin$
#65 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->t$
#66 /home/admin/web/seat.spray.ml/public_html/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Ker$
#67 /home/admin/web/seat.spray.ml/public_html/seat/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#68 {main}


```

**Comment by LordMrcS** [comment]
Hi, there's both, the web debug and the laravel log!

**Comment by warlof** [comment]
Hi @LordMrcS ,

could you switch to our Slack - so we can continue to investigate about your trouble ?

**Comment by LordMrcS** [comment]
@warlof sorry for being absent on this matter. I can, but haven't used it before, what should I do?

**Comment by warlof** [comment]
Hi @LordMrcS 
Well, get your ticket https://eveseat.github.io/docs/about/contact/ and get on the train ;)

**Comment by warlof** [comment]
For information, issue was related to partially applied command from the documentation.
 - https://eveseat.github.io/docs/installation/manual/centos/#nginx-configuration
 - https://eveseat.github.io/docs/installation/manual/debian/#nginx-configuration
 - https://eveseat.github.io/docs/installation/manual/ubuntu/#nginx-configuration

In NGinX section, we're providing you a command which is containing a basic configuration template. This command is inserting backslash character (`\`) to escape variables (`$uri`, `$query_string`, `$document_root`, `$fastcgi_script_name`) which would be interpreted by used prompt.

If you're not running the complete command and only picking the configuration template (or a part of it), please, remember to drop backslahes. Otherwise, you'll encountering issues with url rewriting - especially during OAuth flow.
