### ISSUE TITLE
Cannot log in at all

### ISSUE THREAD

**Issue by Kaoraku** [eveseat/seat#599]
* **Problem**: When the site ask permissions, I gave to him all of it with my main character. But then instead of log in, it says " Error Login failed. Requested access are not matching, please try again."

* **Expected**: I am expected to log in

* **Logs / Screenshots / Proof**: First the other admin thought it is happens cause of some webhook, since the log shows error about notification via webhook - so he cleaned it out from the database. Now there is nothing in the log, but still not able to log in. It was updated by it's own updater, also by hand. We restarted the service, even the whole server. Tried another account also.

```
[2019-11-04 15:20:16] local.ERROR: Client error: `POST https://discordapp.com/api/webhooks/*****` resulted in a `400 BAD REQUEST` response:
{"message": "Cannot send an empty message", "code": 50006}
 {"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 400): Client error: `POST https://discordapp.com/api/webhooks/*****` resulted in a `400 BAD REQUEST` response:
{\"message\": \"Cannot send an empty message\", \"code\": 50006}
 at /var/www/seat/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
[stacktrace]
#0 /var/www/seat/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Psr7\\Request), Object(GuzzleHttp\\Psr7\\Response))
#1 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Response))
#2 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, Object(GuzzleHttp\\Psr7\\Response), Array)
#3 /var/www/seat/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()
#4 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\\Promise\\TaskQueue->run(true)
#5 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#6 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\\Promise\\Promise->waitIfPending()
#7 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#8 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#9 /var/www/seat/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\\Promise\\Promise->wait()
#10 /var/www/seat/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\\Client->request('post', 'https://discord...', Array)
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Notifications/Channels/SlackWebhookChannel.php(45): GuzzleHttp\\Client->__call('post', Array)
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(113): Illuminate\\Notifications\\Channels\\SlackWebhookChannel->send(Object(Seat\\Notifications\\Models\\NotificationGroup), Object(Seat\\Notifications\\Notifications\\MemberTo
kenState))
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(89): Illuminate\\Notifications\\NotificationSender->sendToNotifiable(Object(Seat\\Notifications\\Models\\NotificationGroup), '9bd61958-4b1b-4...', Object(Seat\\Notifications\\N
otifications\\MemberTokenState), 'slack')
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(64): Illuminate\\Notifications\\NotificationSender->sendNow(Object(Illuminate\\Database\\Eloquent\\Collection), Object(Seat\\Notifications\\Notifications\\MemberTokenState))
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(35): Illuminate\\Notifications\\NotificationSender->send(Object(Illuminate\\Database\\Eloquent\\Collection), Object(Seat\\Notifications\\Notifications\\MemberTokenState))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\\Notifications\\ChannelManager->send(Object(Seat\\Notifications\\Models\\NotificationGroup), Object(Seat\\Notifications\\Notifications\\MemberTokenState))
#17 /var/www/seat/vendor/eveseat/notifications/src/Alerts/Base.php(141): Seat\\Notifications\\Models\\NotificationGroup->notify(Object(Seat\\Notifications\\Notifications\\MemberTokenState))
#18 /var/www/seat/vendor/eveseat/notifications/src/Commands/AlertsRun.php(72): Seat\\Notifications\\Alerts\\Base->handle()
#19 [internal function]: Seat\\Notifications\\Commands\\AlertsRun->handle()
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#25 /var/www/seat/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#27 /var/www/seat/vendor/symfony/console/Application.php(982): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 /var/www/seat/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Seat\\Notifications\\Commands\\AlertsRun), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\Cons
oleOutput))
#29 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /var/www/seat/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 {main}
"}
```

* **Version Info**: 
```
SeAT Diagnostics
If you are not already doing so, it is recommended that you run this as the user the workers are running as.
Eg:
    sudo -u apache php artisan seat:admin:diagnose
    su -c "php artisan seat:admin:diagnose" -s /bin/sh www-data
This helps to check whether the permissions are correct.
 
 * Getting environment information
Current User: www-data
PHP Version: 7.3.11-1+ubuntu18.04.1+deb.sury.org+1
Host OS: Linux the1stregiment 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64
SeAT Basepath: /var/www/seat
 
 * Checking DEBUG mode
Debug mode is enabled. This is not recommended in production!
 
 * Checking storage
/var/www/seat/storage is writable
/var/www/seat/storage/logs is writable
/var/www/seat/storage/eseye is writable
/var/www/seat/storage/sde/ is writable
/var/www/seat/storage/logs/laravel-2019-11-04.log is writable
 
 * Checking Database
+------------+------------------+
| Setting    | Value            |
+------------+------------------+
| Connection | mysql            |
| Host       | 127.0.0.1        |
| Database   | ****             |
| Username   | ****             |
| Password   | **************** |
+------------+------------------+
Connection OK to database: seat
 
 * Checking Redis
+----------+-----------+
| Setting  | Value     |
+----------+-----------+
| Host     | 127.0.0.1 |
| Port     | 6379      |
| Database | 0         |
+----------+-----------+
Connected to Redis
Set random key of: *****
Set key to expire in 10 sec
Read key OK
 
 * Checking ESI Access
Server Online Since: 2019-11-04T11:06:19Z
Online Players: 21247
ESI appears to be OK
 
Checking Local and Github Versions. Please wait...
+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 3.0.8         | 3.0.8         |
| Console       | 3.0.5         | 3.0.5         |
| Eveapi        | 3.0.17        | 3.0.17        |
| Notifications | 3.0.6         | 3.0.6         |
| Web           | 3.0.25        | 3.0.25        |
| Services      | 3.0.11        | 3.0.11        |
+---------------+---------------+---------------+
SeAT Diagnostics complete
```

**Comment by warlof** [comment]
Hi,

Ensure you have exactly same scopes between those listed from `SSL Login` and the eve app.

Also, if you just update, hit submit inside the `SSO Login` in order to get updated scopes list.

**Comment by Kaoraku** [comment]
Than you @warlof for the answer, however I not really understand it. I cannot realy do anything about the scopes what listed by the seat. However I am updated (basicly just opened and saved it) at dev.eveonline, and now when it would redirect me to the login form it just says
`{"error":"invalid_scope","error_description":"The requested scopes either don't exist, or are not valid for this client"}`

**Comment by warlof** [comment]
Talking with a screen, the stuff listed on left side must match **exactly** the stuff listed on the right side.
 - left side is your `SeAT > Settings > Single Sign-on (SSO)`
 - right side is your `EVE Online App Permissions`

![image](https://user-images.githubusercontent.com/648753/68148788-f54b8a80-ff3c-11e9-99ba-4d14ec48b0a7.png)

**Comment by Kaoraku** [comment]
Thank you for your help! I checked the scopes one-by-one, and now I think the list is right - we able to log in the site.
