### ISSUE TITLE
Scheduler Key Errors 

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#63]
```
Last Updater: Started APIKeyInfo Update

Exception: Seat\Eveapi\Exception\InvalidKeyPairException
Error Code: 0
Error Message: 
File: /var/www/seat/vendor/eveseat/eveapi/src/Traits/Validation.php - Line: 52

Traceback: #0 /var/www/seat/vendor/eveseat/eveapi/src/Api/Base.php(117): Seat\Eveapi\Api\Base->validateKeyPair('5016321', '')
#1 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/CheckAndQueueKey.php(95): Seat\Eveapi\Api\Base->setApi(Object(Seat\Eveapi\Models\Eve\ApiKey))
#2 [internal function]: Seat\Eveapi\Jobs\CheckAndQueueKey->handle(Object(Seat\Eveapi\Helpers\JobContainer))
#3 /var/www/seat/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array)
#4 /var/www/seat/bootstrap/cache/compiled.php(9441): Illuminate\Container\Container->call(Array)
#5 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\CheckAndQueueKey))
#6 /var/www/seat/bootstrap/cache/compiled.php(9593): call_user_func(Object(Closure), Object(Seat\Eveapi\Jobs\CheckAndQueueKey))
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\CheckAndQueueKey))
#8 /var/www/seat/bootstrap/cache/compiled.php(9575): call_user_func(Object(Closure), Object(Seat\Eveapi\Jobs\CheckAndQueueKey))
#9 /var/www/seat/bootstrap/cache/compiled.php(9448): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(43): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\CheckAndQueueKey), Object(Closure))
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/RedisJob.php(50): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(208): Illuminate\Queue\Jobs\RedisJob->fire()
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), '10', '0')
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(109): Illuminate\Queue\Worker->pop('', 'high,medium,low...', '0', '3', '10')
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(71): Illuminate\Queue\Console\WorkCommand->runWorker('', 'high,medium,low...', '0', '128', false)
#17 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#18 /var/www/seat/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array)
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#20 /var/www/seat/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/seat/vendor/symfony/console/Application.php(841): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/seat/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/seat/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/seat/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 {main}
```

I get a lot of these errors on various keys in after the update to the latest version of seat.  Anything you all need me to do to help you figure this out?

**Comment by drkthunder02** [comment]
Another note for you all when I get these errors I get a lot of jobs sitting in my queues as working jobs, even though I only have 4 workers present for Supervisor.

**Comment by warlof** [comment]
it's appearing there is an issue with 5016321 api
i recommand you to forward it up to qu1ckkk if possible ini order to help him with debugging.

**Comment by leonjza** [comment]
Please make 100% sure you are on the latest versions. This should have been fixed in `eveseat/web` 1.0.21. Also, try re-adding the problematic keys as the problem was actually the way the keys were stored in the database.

As for the stuck jobs, you can clear the queue with `php artisan seat:cache:clear`

**Comment by leonjza** [comment]
Ping @drkthunder02

**Comment by drkthunder02** [comment]
I'll update again tonight.

**Comment by leonjza** [comment]
Re add the keys that may have had this error. A bug relating to this was recently fixed in the `web` package.
