### ISSUE TITLE
There is a problem when using redis with password

### ISSUE THREAD

**Issue by KagurazakaNyaa** [eveseat/seat#649]
* **Problem**: After updating SeAT 4, the redis configuration in config/database.php has been updated to use php-redis, but laravel/horizon version 3 (not version 4) and eveseat/eseye still use predis as the redis driver.
This resulted in a large number of error logs, and at the same time caused the error of `Redis test failed. NOAUTH Authentication required.` to be reported in the `Checking Redis` section when using `php artisan seat:admin:diagnose`.
* **Expected**: The redis driver used by the entire framework should use the same configuration, or at least pass the php-redis configuration to predis to prevent password problems. I think the best solution is to migrate eseye from predis to php-redis and use the new version at the same time The horizon.
* **Logs / Screenshots / Proof**: There are a lot of logs, but the content is basically repeated. I excerpt one of the repeated content here.
```
[2020-08-24 01:50:27] local.ERROR: `AUTH` failed: ERR invalid password [tcp://database.kagurazakanyaa.com:6379] {"exception":"[object] (Predis\\Connection\\ConnectionException(code: 0): `AUTH` failed: ERR invalid password [tcp://database.kagurazakanyaa.com:6379] at /var/www/seat/vendor/predis/predis/src/Connection/AbstractConnection.php:155)
[stacktrace]
#0 /var/www/seat/vendor/predis/predis/src/Connection/StreamConnection.php(263): Predis\\Connection\\AbstractConnection->onConnectionError('`AUTH` failed: ...', 0)
#1 /var/www/seat/vendor/predis/predis/src/Connection/AbstractConnection.php(180): Predis\\Connection\\StreamConnection->connect()
#2 /var/www/seat/vendor/predis/predis/src/Connection/StreamConnection.php(288): Predis\\Connection\\AbstractConnection->getResource()
#3 /var/www/seat/vendor/predis/predis/src/Connection/StreamConnection.php(394): Predis\\Connection\\StreamC\nnection->write('*4\
\16\
ZREVRA...')
#4 /var/www/seat/vendor/predis/predis/src/Connection/AbstractConnection.php(110): Predis\\Connection\\StreamConnection->writeRequest(Object(Predis\\Command\\ZSetReverseRangeByScore))
#5 /var/www/seat/vendor/predis/predis/src/Client.php(331): Predis\\Connection\\AbstractConnection->executeCommand(Object(Predis\\Command\\ZSetReverseRangeByScore))
#6 /var/www/seat/vendor/predis/predis/src/Client.php(314): Predis\\Client->executeCommand(Object(Predis\\Command\\ZSetReverseRangeByScore))
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(96): Predis\\Client->__call('zrevrangebyscor...', Array)
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(108): Illuminate\\Redis\\Connections\\Connection->command('zrevrangebyscor...', Array)
#9 /var/www/seat/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(39): Illuminate\\Redis\\Connections\\Connection->__call('zrevrangebyscor...', Array)
#10 /var/www/seat/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(50): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->names()
#11 /var/www/seat/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(99): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->all()
#12 /var/www/seat/vendor/laravel/horizon/src/MasterSupervisor.php(166): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->longestActiveTimeout()
#13 /var/www/seat/vendor/laravel/horizon/src/ListensForSignals.php(52): Laravel\\Horizon\\MasterSupervisor->terminate()
#14 /var/www/seat/vendor/laravel/horizon/src/MasterSupervisor.php(238): Laravel\\Horizon\\MasterSupervisor->processPendingSignals()
#15 /var/www/seat/vendor/laravel/horizon/src/MasterSupervisor.php(213): Laravel\\Horizon\\MasterSupervisor->loop()
#16 /var/www/seat/vendor/laravel/horizon/src/Console/HorizonCommand.php(64): Laravel\\Horizon\\MasterSupervisor->monitor()
#17 [internal function]: Laravel\\Horizon\\Console\\HorizonCommand->handle()
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#23 /var/www/seat/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#25 /var/www/seat/vendor/symfony/console/Application.php(987): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /var/www/seat/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\HorizonCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /var/www/seat/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 {main}
"} 
```
There are a lot of error logs every day, but basically the content is like this.
```
root@waw-eve:/var/www/seat/storage/logs# ll -h
总用量 8.8G
-rw-r--r-- 1 www-data www-data  37M 8月  18 07:59 eseye-2020-08-17.log
-rw-r--r-- 1 www-data www-data  54M 8月  19 07:59 eseye-2020-08-18.log
-rw-r--r-- 1 www-data www-data  52M 8月  20 07:59 eseye-2020-08-19.log
-rw-r--r-- 1 www-data www-data  39M 8月  21 07:59 eseye-2020-08-20.log
-rw-r--r-- 1 www-data www-data  55M 8月  22 07:59 eseye-2020-08-21.log
-rw-r--r-- 1 www-data www-data  55M 8月  23 07:59 eseye-2020-08-22.log
-rw-r--r-- 1 www-data www-data  37M 8月  24 07:59 eseye-2020-08-23.log
-rw-r--r-- 1 www-data www-data 2.5M 8月  24 09:52 eseye-2020-08-24.log
-rw-r--r-- 1 www-data www-data 1.2G 8月  21 07:59 laravel-2020-08-20.log
-rw-r--r-- 1 www-data www-data 1.7G 8月  22 07:59 laravel-2020-08-21.log
-rw-r--r-- 1 www-data www-data 1.5G 8月  23 07:59 laravel-2020-08-22.log
-rw-r--r-- 1 www-data www-data 3.9G 8月  24 07:59 laravel-2020-08-23.log
-rw-r--r-- 1 www-data www-data 348M 8月  24 09:52 laravel-2020-08-24.log
```
* **Version Info**: 
```
php -v
PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
```
```
uname -a
Linux waw-eve.com 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
```

| Package Name  | Local Version | Latest Github |
|---------------|---------------|---------------|
| Api           | 4.0.0         | 4.0.0         |
| Console       | 4.0.4         | 4.0.4         |
| Eveapi        | 4.1.1         | 4.1.1         |
| Notifications | 4.0.2         | 4.0.2         |
| Web           | 4.1.6         | 4.1.6         |
| Services      | 4.0.0         | 4.0.0         |

**Comment by warlof** [comment]
Hi,

that's odd, php-redis is now the default driver used by Laravel.
can you do the following two things for me ?

1) `php artisan tinker` will open you a debug console
2) `config('database.redis')` will print you some information that you can paste here (exclude password if you have one)
3) `get_loaded_extensions()` will show you a list of installed extensions

once done, leave the console using `exit`

**Comment by KagurazakaNyaa** [comment]
```
root@waw-eve:/var/www/seat# sudo -u www-data php artisan tinker
Psy Shell v0.9.12 (PHP 7.3.19-1~deb10u1 — cli) by Justin Hileman
>>> config('database.redis')
=> [
     "client" => "phpredis",
     "options" => [
       "cluster" => "redis",
       "prefix" => "seat_database_",
     ],
     "default" => [
       "url" => null,
       "host" => "database.kagurazakanyaa.com",
       "password" => "redacted",
       "port" => "6379",
       "database" => 0,
     ],
     "cache" => [
       "url" => null,
       "host" => "database.kagurazakanyaa.com",
       "password" => "redacted",
       "port" => "6379",
       "database" => 1,
     ],
     "horizon" => [
       "url" => null,
       "host" => "database.kagurazakanyaa.com",
       "password" => "redacted",
       "port" => "6379",
       "database" => 0,
       "options" => [
         "prefix" => "horizon:",
       ],
     ],
   ]
>>> get_loaded_extensions()
=> [
     "Core",
     "date",
     "libxml",
     "openssl",
     "pcre",
     "zlib",
     "filter",
     "hash",
     "pcntl",
     "Reflection",
     "SPL",
     "session",
     "sodium",
     "standard",
     "mysqlnd",
     "PDO",
     "xml",
     "bcmath",
     "bz2",
     "calendar",
     "ctype",
     "curl",
     "dom",
     "enchant",
     "mbstring",
     "fileinfo",
     "ftp",
     "gd",
     "geoip",
     "gettext",
     "gmp",
     "iconv",
     "igbinary",
     "imagick",
     "imap",
     "interbase",
     "intl",
     "json",
     "ldap",
     "exif",
     "mysqli",
     "PDO_Firebird",
     "pdo_mysql",
     "Phar",
     "posix",
     "readline",
     "redis",
     "shmop",
     "SimpleXML",
     "soap",
     "sockets",
     "sysvmsg",
     "sysvsem",
     "sysvshm",
     "tokenizer",
     "uuid",
     "wddx",
     "xmlreader",
     "xmlrpc",
     "xmlwriter",
     "xsl",
     "zip",
     "Zend OPcache",
   ]
```

**Comment by KagurazakaNyaa** [comment]
There is the [compose.lock](https://pastebin.ubuntu.com/p/4vbDNYCVGr/) of this instance.

**Comment by KagurazakaNyaa** [comment]
In addition, after connecting to the redis instance via `redis-cli` and using the `monitor` command, I found that the redis key belonging to SeAT was updated and read normally. At the same time, in the use of SeAT, apart from a large number of error logs, no other errors caused by redis were found.

**Comment by warlof** [comment]
can you add output of all your installed composer package with `composer show` at seat root directory ?

thank you

**Comment by KagurazakaNyaa** [comment]
```
root@waw-eve:/var/www/seat# sudo -u www-data composer show
almasaeed2010/adminlte                  v3.0.5            AdminLTE - admin control panel and dashboard...
brick/math                              0.8.17            Arbitrary-precision arithmetic library
cakephp/chronos                         1.3.0             A simple API extension for DateTime.
coduo/php-humanizer                     3.0.2             Humanize values that are readable only for d...
components/font-awesome                 5.14.0            Font Awesome, the iconic SVG, font, and CSS ...
darkaonline/l5-swagger                  6.0.5             Swagger integration to Laravel 5
datatables/datatables                   1.10.21           DataTables is a plug-in for the jQuery Javas...
denngarr/seat-fitting                   4.0.x-dev 8cf28ba Module to check fittings per character
denngarr/seat-srp                       4.0.0-alpha       A module for SeAT that tracks SRP requests
dnoegel/php-xdg-base-dir                v0.1.1            implementation of xdg base directory specifi...
doctrine/annotations                    1.10.4            Docblock Annotations Parser
doctrine/cache                          1.10.2            PHP Doctrine Cache library is a popular cach...
doctrine/dbal                           2.10.2            Powerful PHP database abstraction layer (DBA...
doctrine/event-manager                  1.1.1             The Doctrine Event Manager is a simple PHP e...
doctrine/inflector                      2.0.3             PHP Doctrine Inflector is a small library th...
doctrine/lexer                          1.2.1             PHP Doctrine Lexer parser library that can b...
dragonmantank/cron-expression           v2.3.0            CRON for PHP: Calculate the next or previous...
egulias/email-validator                 2.1.19            A library for validating emails against seve...
erusev/parsedown                        1.7.4             Parser for Markdown.
eveseat/api                             4.0.0             SeAT API Interface
eveseat/console                         4.0.4             SeAT Console Components
eveseat/eseye                           2.2.2             A Standalone PHP ESI (EVE Swagger Interface)...
eveseat/eveapi                          4.1.1             SeAT EVE API Integration
eveseat/notifications                   4.0.2             SeAT Notifications Components
eveseat/services                        4.0.0             SeAT Services Components
eveseat/web                             4.1.6             SeAT Web Interface
fgrosse/phpasn1                         v2.1.1            A PHP Framework that allows you to encode an...
fideloper/proxy                         4.4.0             Set trusted proxies for Laravel
guzzlehttp/guzzle                       6.5.5             Guzzle is a PHP HTTP client library
guzzlehttp/promises                     v1.3.1            Guzzle promises library
guzzlehttp/psr7                         1.6.1             PSR-7 message implementation that also provi...
intervention/image                      2.5.1             Image handling and manipulation library with...
jakub-onderka/php-console-color         v0.2             
jakub-onderka/php-console-highlighter   v0.4              Highlight PHP code in terminal
kassie/calendar                         4.0.0             Calendar plugin for SeAT.
laravel/framework                       v6.18.35          The Laravel Framework.
laravel/horizon                         v3.7.2            Dashboard and code-driven configuration for ...
laravel/slack-notification-channel      v2.1.0            Slack Notification Channel for laravel.
laravel/socialite                       v4.4.1            Laravel wrapper around OAuth 1 & OAuth 2 lib...
laravel/tinker                          v1.0.10           Powerful REPL for the Laravel framework.
laravelcollective/html                  v6.1.2            HTML and Form Builders for the Laravel Frame...
lasserafn/php-initial-avatar-generator  4.1.1             A package to generate avatars with initials ...
lasserafn/php-initials                  3.0               A package to generate initials in PHP
lasserafn/php-string-script-language    0.1               Detect language/encoding of a string in PHP
league/commonmark                       1.5.4             Highly-extensible PHP Markdown parser which ...
league/flysystem                        1.1.3             Filesystem abstraction: Many filesystems, on...
league/mime-type-detection              1.4.0             Mime-type detection for Flysystem
league/oauth1-client                    1.7.0             OAuth 1.0 Client Library
maatwebsite/excel                       3.1.21            Supercharged Excel exports and imports in La...
maennchen/zipstream-php                 2.1.0             ZipStream is a library for dynamically strea...
markbaker/complex                       1.4.8             PHP Class for working with complex numbers
markbaker/matrix                        1.2.0             PHP Class for working with matrices
meyfa/php-svg                           v0.9.1            Read, edit, write, and render SVG files with...
monolog/monolog                         2.1.1             Sends your logs to files, sockets, inboxes, ...
myclabs/php-enum                        1.7.6             PHP Enum implementation
nesbot/carbon                           2.38.0            An API extension for DateTime that supports ...
nikic/php-parser                        v4.9.0            A PHP parser written in PHP
opis/closure                            3.5.6             A library that can be used to serialize clos...
overtrue/pinyin                         4.0.6             Chinese to pinyin translator.
paragonie/random_compat                 v9.99.99          PHP 5.x polyfill for random_bytes() and rand...
phpoffice/phpspreadsheet                1.14.1            PHPSpreadsheet - Read, Create and Write Spre...
phpoption/phpoption                     1.7.5             Option Type for PHP
predis/predis                           v1.1.3            Flexible and feature-complete Redis client f...
psr/container                           1.0.0             Common Container Interface (PHP FIG PSR-11)
psr/http-client                         1.0.1             Common interface for HTTP clients
psr/http-factory                        1.0.1             Common interfaces for PSR-7 HTTP message fac...
psr/http-message                        1.0.1             Common interface for HTTP messages
psr/log                                 1.1.3             Common interface for logging libraries
psr/simple-cache                        1.0.1             Common interfaces for simple caching
psy/psysh                               v0.9.12           An interactive shell for modern PHP.
ralouphie/getallheaders                 3.0.3             A polyfill for getallheaders.
ramsey/uuid                             3.9.3             Formerly rhumsaa/uuid. A PHP 5.4+ library fo...
s9e/regexp-builder                      1.4.4             Single-purpose library that generates regula...
s9e/sweetdom                            1.0.1             Syntactic sugar for the DOM API with a focus...
s9e/text-formatter                      2.7.4             Multi-purpose text formatting and markup lib...
socialiteproviders/manager              v3.5              Easily add new or override built-in provider...
spomky-labs/base64url                   v2.0.2            Base 64 URL Safe Encoding/Decoding PHP Library
swagger-api/swagger-ui                  v3.32.4            Swagger UI is a collection of HTML, Javascr...
swiftmailer/swiftmailer                 v6.2.3            Swiftmailer, free feature-rich PHP mailer
symfony/config                          v4.4.11           Symfony Config Component
symfony/console                         v4.4.11           Symfony Console Component
symfony/css-selector                    v5.1.3            Symfony CssSelector Component
symfony/debug                           v4.4.11           Symfony Debug Component
symfony/error-handler                   v4.4.11           Symfony ErrorHandler Component
symfony/event-dispatcher                v4.4.11           Symfony EventDispatcher Component
symfony/event-dispatcher-contracts      v1.1.9            Generic abstractions related to dispatching ...
symfony/filesystem                      v5.1.3            Symfony Filesystem Component
symfony/finder                          v4.4.11           Symfony Finder Component
symfony/http-foundation                 v4.4.11           Symfony HttpFoundation Component
symfony/http-kernel                     v4.4.11           Symfony HttpKernel Component
symfony/mime                            v5.1.3            A library to manipulate MIME messages
symfony/polyfill-ctype                  v1.18.1           Symfony polyfill for ctype functions
symfony/polyfill-iconv                  v1.18.1           Symfony polyfill for the Iconv extension
symfony/polyfill-intl-idn               v1.18.1           Symfony polyfill for intl's idn_to_ascii and...
symfony/polyfill-intl-normalizer        v1.18.1           Symfony polyfill for intl's Normalizer class...
symfony/polyfill-mbstring               v1.18.1           Symfony polyfill for the Mbstring extension
symfony/polyfill-php70                  v1.18.1           Symfony polyfill backporting some PHP 7.0+ f...
symfony/polyfill-php72                  v1.18.1           Symfony polyfill backporting some PHP 7.2+ f...
symfony/polyfill-php73                  v1.18.1           Symfony polyfill backporting some PHP 7.3+ f...
symfony/polyfill-php80                  v1.18.1           Symfony polyfill backporting some PHP 8.0+ f...
symfony/process                         v4.4.11           Symfony Process Component
symfony/routing                         v4.4.11           Symfony Routing Component
symfony/service-contracts               v2.1.3            Generic abstractions related to writing serv...
symfony/translation                     v4.4.11           Symfony Translation Component
symfony/translation-contracts           v2.1.3            Generic abstractions related to translation
symfony/var-dumper                      v4.4.11           Symfony mechanism for exploring and dumping ...
symfony/yaml                            v4.4.11           Symfony Yaml Component
tijsverkoyen/css-to-inline-styles       2.2.3             CssToInlineStyles is a class that enables yo...
twbs/bootstrap                          v4.5.2            The most popular front-end framework for dev...
vlucas/phpdotenv                        v3.6.7            Loads environment variables from `.env` to `...
web-token/jwt-checker                   v2.2.0            Checker component of the JWT Framework.
web-token/jwt-core                      v2.2.0            Core component of the JWT Framework.
web-token/jwt-easy                      v2.2.0            Easy toolset to use the JWT Framework.
web-token/jwt-encryption                v2.2.0            Encryption component of the JWT Framework.
web-token/jwt-signature                 v2.2.0            Signature component of the JWT Framework.
web-token/jwt-signature-algorithm-ecdsa v2.2.0            ECDSA Based Signature Algorithms the JWT Fra...
web-token/jwt-signature-algorithm-hmac  v2.2.0            HMAC Based Signature Algorithms the JWT Fram...
web-token/jwt-signature-algorithm-rsa   v2.2.0            RSA Based Signature Algorithms the JWT Frame...
yajra/laravel-datatables-buttons        v4.9.3            Laravel DataTables Buttons Plugin.
yajra/laravel-datatables-html           v4.30.0           Laravel DataTables HTML builder plugin for L...
yajra/laravel-datatables-oracle         v9.10.2           jQuery DataTables API for Laravel 4|5|6|7
zircote/swagger-php                     3.0.4             swagger-php - Generate interactive documenta...
```

**Comment by wfjsw** [comment]
Did you restart the horizon daemon after doing any changes to the project files?

**Comment by KagurazakaNyaa** [comment]
> Did you restart the horizon daemon after doing any changes to the project files?

Of course, the supervisor service will be restarted after every modification.

**Comment by wfjsw** [comment]
Fine. Please enter `php artisan tinker`, run `resolve('redis.connection')` and paste the result here.

**Comment by KagurazakaNyaa** [comment]
```
root@waw-eve:/var/www/seat# sudo -u www-data php artisan tinker
Psy Shell v0.9.12 (PHP 7.3.19-1~deb10u1 — cli) by Justin Hileman
>>> resolve('redis.connection')
=> Illuminate\Redis\Connections\PhpRedisConnection {#4862}
```

**Comment by wfjsw** [comment]
你这个里边有很多怪事，首先eseye如果不改改vendor/里的源码的话是没有rediscache用的。但是这个cache实际上没什么用，建议直接关掉。

另外现在我很难相信你真的正确的重启了horizon。试试kill掉再开？

**Comment by KagurazakaNyaa** [comment]
> 你这个里边有很多怪事，首先eseye如果不改改vendor/里的源码的话是没有rediscache用的。但是这个cache实际上没什么用，建议直接关掉。
> 
> 另外现在我很难相信你真的正确的重启了horizon。试试kill掉再开？

在使用`systemctl stop supervisor`并使用`kill -9`终止了所有的horizon进程之后，重新启动supervisor后似乎问题修复了，但是为什么会出现此问题呢?

**Comment by wfjsw** [comment]
难道不是 `supervisorctl restart horizon` 么（

**Comment by KagurazakaNyaa** [comment]
> 难道不是 `supervisorctl restart horizon` 么（

之前是使用`supervisorctl restart all`，然而问题持续，直到停止supervisor服务进程并手动终止两个horizon进程后重新启动

**Comment by wfjsw** [comment]
那可能是没杀干净

**Comment by KagurazakaNyaa** [comment]
> 那可能是没杀干净

有可能，难道这个horizon进程是之前seat3遗留下来的吗......
