### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by elrond1975** [eveseat/seat#783]
Hi.
After updating the packages, the server stopped running with error 500.

*** **Problem**: Server Error 500**

* **Logs / Screenshots / Proof**: _The more information you give the better!_
[2021-03-12 13:36:24] local.ERROR: Erroneous data format for unserializing 'Symfony\Component\Routing\CompiledRoute' {"exception":"[object] (ErrorException(code: 0): Erroneous data format for unserializing 'Symfony\\Component\\Routing\\CompiledRoute' at /var/www/seat/bootstrap/cache/routes.php:15)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Erroneous data ...', '/var/www/seat/b...', 15, Array)
#1 /var/www/seat/bootstrap/cache/routes.php(15): unserialize('O:34:\"Illuminat...')
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(75): require('/var/www/seat/b...')
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(895): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->Illuminate\\Foundation\\Support\\Providers\\{closure}(Object(Illuminate\\Foundation\\Application))
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(844): Illuminate\\Foundation\\Application->fireAppCallbacks(Array)
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(219): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(156): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#10 /var/www/seat/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#11 {main}
"} 

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
[2021-03-12 13:36:24] local.ERROR: Erroneous data format for unserializing 'Symfony\Component\Routing\CompiledRoute' {"exception":"[object] (ErrorException(code: 0): Erroneous data format for unserializing 'Symfony\\Component\\Routing\\CompiledRoute' at /var/www/seat/bootstrap/cache/routes.php:15)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Erroneous data ...', '/var/www/seat/b...', 15, Array)
#1 /var/www/seat/bootstrap/cache/routes.php(15): unserialize('O:34:\"Illuminat...')
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(75): require('/var/www/seat/b...')
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(895): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->Illuminate\\Foundation\\Support\\Providers\\{closure}(Object(Illuminate\\Foundation\\Application))
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(844): Illuminate\\Foundation\\Application->fireAppCallbacks(Array)
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(219): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(156): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#10 /var/www/seat/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#11 {main}
"}

**Comment by elrond1975** [comment]
https://c2n.me/4bhpwuI

**Comment by elrond1975** [comment]
ty :)
problem in ver. php
