### ISSUE TITLE
SeAT is killing Supervisord

### ISSUE THREAD

**Issue by shibdib** [eveseat/seat#82]
```
2016-03-24 01:25:10,531 INFO success: seat-8001 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-03-24 01:25:10,531 INFO success: seat-8000 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-03-24 01:25:10,531 INFO success: seat-8003 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-03-24 01:25:10,531 INFO success: seat-8002 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-03-24 01:45:26,944 INFO exited: seat-8001 (exit status 1; not expected)
2016-03-24 01:45:27,384 INFO spawned: 'seat-8001' with pid 6965
2016-03-24 01:45:28,519 INFO success: seat-8001 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-03-24 01:45:30,188 INFO exited: seat-8000 (exit status 255; not expected)
2016-03-24 01:45:30,215 INFO spawned: 'seat-8000' with pid 6973
2016-03-24 01:45:30,347 INFO exited: seat-8001 (exit status 0; expected)
2016-03-24 01:45:31,348 INFO success: seat-8000 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-03-24 02:20:16,501 INFO exited: seat-8002 (exit status 255; not expected)
2016-03-24 02:20:17,515 INFO spawned: 'seat-8002' with pid 16105
2016-03-24 02:20:18,524 INFO success: seat-8002 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-03-24 02:20:19,397 INFO exited: seat-8002 (exit status 255; not expected)
2016-03-24 02:20:19,594 INFO spawned: 'seat-8002' with pid 16108
2016-03-24 02:20:20,596 INFO success: seat-8002 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-03-24 02:35:16,579 INFO exited: seat-8002 (exit status 0; expected)
2016-03-24 02:35:54,295 INFO exited: seat-8003 (exit status 255; not expected)
2016-03-24 02:35:55,338 INFO spawned: 'seat-8003' with pid 20334
2016-03-24 02:35:56,355 INFO success: seat-8003 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-03-24 02:35:58,692 INFO exited: seat-8000 (exit status 255; not expected)
2016-03-24 02:35:59,409 INFO spawned: 'seat-8000' with pid 20342
2016-03-24 02:35:59,428 INFO exited: seat-8000 (exit status 127; not expected)
2016-03-24 02:36:01,228 INFO spawnerr: unknown error: ENOMEM
```

Supervisord is then completely dead after this. Not sure why, gonna bump the workers down to 2 tho and see if that changes anything.

**Comment by shibdib** [comment]
Seems to be a memory issue, which is weird because it's never happened before.

**Comment by shibdib** [comment]
```
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in /var/www/seat/vendor/symfony/console/Application.php:943
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'proc_open(): fo...', '/var/www/seat/v...', 943, Array)
#1 /var/www/seat/vendor/symfony/console/Application.php(943): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 /var/www/seat/vendor/symfony/console/Application.php(751): Symfony\Component\Console\Application->getSttyColumns()
#3 /var/www/seat/vendor/symfony/console/Application.php(712): Symfony\Component\Console\Application->getTerminalDimensions()
#4 /var/www/seat/vendor/symfony/console/Application.php(645): Symfony\Component\Console\Application->getTerminalWidth()
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(127): Symfony\Component\Console\Application->renderException(Object(Symfony\Component\Debug\Exception\FatalErrorException), O in /var/www/seat/vendor/symfony/console/Application.php on line 943

```

**Comment by shibdib** [comment]
cant for sure say this is a seat issue so closing for now
