### ISSUE TITLE
Seat\Eveapi\Jobs\Corporation\RoleHistories Fails

### ISSUE THREAD

**Issue by qarmotsu** [eveseat/seat#861]
* **Problem**:Seat\Eveapi\Jobs\Corporation\RoleHistories fails all the time

* **Logs / Screenshots / Proof**: 
* Seat\Eveapi\Jobs\Corporation\RoleHistories
ID
28412
Queue
corporations
Tags
corporation, role, 98677713
Failed At
2022-02-15 15:22:46

```
Exception
Seat\Eveapi\Exception\TemporaryEsiOutageException: Internal Error in /var/www/seat/vendor/eveseat/eveapi/src/Jobs/EsiBase.php:480
Stack trace:
#0 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/EsiBase.php(283): Seat\Eveapi\Jobs\EsiBase->handleEsiFailedCall(Object(Seat\Eseye\Exceptions\RequestFailedException))
#1 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Corporation/RoleHistories.php(82): Seat\Eveapi\Jobs\EsiBase->retrieve(Array)
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Seat\Eveapi\Jobs\Corporation\RoleHistories->handle()
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories))
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories))
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories), false)
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories))
#13 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/WithoutOverlapping.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories))
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\Eveapi\Jobs\Middleware\WithoutOverlapping->handle(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories), Object(Closure))
#15 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/RequireCorporationRole.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\Eveapi\Jobs\Middleware\RequireCorporationRole->handle(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories), Object(Closure))
#17 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/IgnoreNpcCorporation.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories))
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\Eveapi\Jobs\Middleware\IgnoreNpcCorporation->handle(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories), Object(Closure))
#19 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckTokenVersion.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories))
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\Eveapi\Jobs\Middleware\CheckTokenVersion->handle(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories), Object(Closure))
#21 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckTokenScope.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\Eveapi\Jobs\Middleware\CheckTokenScope->handle(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories), Object(Closure))
#23 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckServerStatus.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\Eveapi\Jobs\Middleware\CheckServerStatus->handle(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories), Object(Closure))
#25 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckEsiRateLimit.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories))
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\Eveapi\Jobs\Middleware\CheckEsiRateLimit->handle(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories), Object(Closure))
#27 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckEsiStatus.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\Eveapi\Jobs\Middleware\CheckEsiStatus->handle(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories), Object(Closure))
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\Corporation\RoleHistories))
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\RedisJob), Object(Seat\Eveapi\Jobs\Corporation\RoleHistories))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(368): Illuminate\Queue\Jobs\Job->fire()
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon('redis', 'corporations', Object(Illuminate\Queue\WorkerOptions))
#37 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'corporations')
#38 /var/www/seat/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
#39 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#40 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#41 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#42 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#43 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#44 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#45 /var/www/seat/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#46 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#47 /var/www/seat/vendor/symfony/console/Application.php(1009): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#48 /var/www/seat/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#49 /var/www/seat/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#50 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#51 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#52 /var/www/seat/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#53 {main}
```

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
![Screenshot at Feb 15 16-19-34](https://user-images.githubusercontent.com/80980799/154092047-c8353341-4fc9-47a3-9c05-c0d6f3e19bee.png)

**Comment by warlof** [comment]
Can you make a quick check ?

Go to this website : https://esi.evetech.net

1. Top right, click on authorize button
2. search and check `esi-corporations.read_corporation_membership.v1`
3. click on authorize button, authenticate with a character in failing corporation having `Director` role (or beeing CEO)
4. go to https://esi.evetech.net/ui/#/Corporation/get_corporations_corporation_id_roles_history (or search for `Get corporation member roles history`
5. click on `Try it out`
6. fill the corporation field (you'll get the value from either failing job or onto any related SeAT corporation page)
7. click on `Execute`

Report if response was either success (code 200) - or something else (with the specified error, if any)

![image](https://user-images.githubusercontent.com/648753/154337544-731c766a-c1da-4a72-92de-b25d2765387b.png)

**Comment by bigboosss** [comment]
FYI, I have the same error on my seat

![image](https://user-images.githubusercontent.com/80131775/154343540-763ad547-40a0-42bd-b74c-4f74019d58d4.png)

**Comment by warlof** [comment]
So unfortunately, this is a thing which have to be sort by CCP.
You can open an issue there if none related already exists https://github.com/esi/esi-issues/issues

You can use this process to fulfill the issue since all requested information are provided by it.

**Comment by veteranmina** [comment]
Please refer to this issue in ESI - https://github.com/esi/esi-issues/issues/1318
